$JOB ASSEMBLE CCL AND LINK
/OBJ: IS THE OUTPUT DEVICE; SRCE: IS THE INPUT DEVICE
/BOTH MUST BE DEFINED AT THIS LEVEL.
.DEL CCLV4.MP

.MAC OBJ:<SRCE:CCLAT
.MAC OBJ:<SRCE:CCLDAT
.MAC OBJ:<SRCE:CCLCOR
.MAC OBJ:<SRCE:CCLCD
.MAC OBJ:<SRCE:CCLSUB
.MAC OBJ:<SRCE:CCLSB2
.MAC OBJ:<SRCE:CCLREM
.MAC OBJ:<SRCE:CCLMSG
.MAC OBJ:<SRCE:CCL
.MAC OBJ:<SRCE:CCLTBL
.MAC OBJ:<SRCE:CCLTAB
.MAC OBJ:<SRCE:CCLRUN
.MAC OBJ:<SRCE:CCLDRV
.MAC OBJ:<SRCE:CCLPS
.MAC OBJ:<SRCE:CCLSIZ
.MAC OBJ:<SRCE:CCLCDX

.R LINK
*SYS:CCL.V4,SYS:CCLV4<OBJ:CCL,CCLTBL,CCLAT,CCLMSG,CCLTAB/F
*OBJ:CCLDRV,CCLPS,CCLSIZ/F
*=0/N/9
*=1000/N
*=1400/N
*=2000/N
*=2400/N
*=3000/N
*=3400/N
*=4000/N
*=4400/N/O
*OBJ:CCLDAT,CCLCOR/C
*OBJ:CCLSUB/C
*OBJ:CCLSB2/C
*OBJ:CCLCDX
*/O
*OBJ:CCLCD/C
*OBJ:CCLRUN,CCLREM
*$

.DEL OBJ:*.RB
.LIST CCLV4.MP

$END

