$JOB ASSEMBLE AND LINK THE FORTRAN LIBRARY.

/REQURES ASSIGNMENT OF DEV1: AS OUTPUT DEVICE. INPUT IS SYS:


.R RALF
*DEV1:ABS.RL<DEV2:ABS.RA
.R RALF
*DEV1:ASIN.RL<DEV2:ASIN.RA
.R RALF
*DEV1:ATAN.RL<DEV2:ATAN.RA
.R RALF
*DEV1:EXP.RL<DEV2:EXP.RA
.R RALF
*DEV1:IFIX.RL<DEV2:IFIX.RA
.R RALF
*DEV1:SINH.RL<DEV2:SINH.RA
.R RALF
*DEV1:AMOD.RL<DEV2:AMOD.RA
.R RALF
*DEV1:COSH.RL<DEV2:COSH.RA
.R RALF
*DEV1:ACOS.RL<DEV2:ACOS.RA
.R RALF
*DEV1:ONQIB.RL<DEV2:ONQIB.RA
.R RALF
*DEV1:SIGN.RL<DEV2:SIGN.RA
.R RALF
*DEV1:TANH.RL<DEV2:TANH.RA
.R RALF
*DEV1:EXPII.RL<DEV2:EXPII.RA
.R RALF
*DEV1:LTR.RL<DEV2:LTR.RA
.R RALF
*DEV1:SIN.RL<DEV2:SIN.RA
.R RALF
*DEV1:TAN.RL<DEV2:TAN.RA
.R RALF
*DEV1:ALOG.RL<DEV2:ALOG.RA
.R RALF
*DEV1:AMIN.RL<DEV2:AMIN.RA
.R RALF
*DEV1:EXP3.RL<DEV2:EXP3.RA
.R RALF
*DEV1:COS.RL<DEV2:COS.RA
.R RALF
*DEV1:CHKEOF.RL<DEV2:CHKEOF.RA
.R RALF
*DEV1:RFDV.RL<DEV2:RFDV.RA
.R RALF
*DEV1:RFCV.RL<DEV2:RFCV.RA
.R RALF
*DEV1:PAUSE.RL<DEV2:PAUSE.RA
.R RALF
*DEV1:CLK8A.RL<DEV2:CLK8A.RA
.R RALF
*DEV1:AMAX.RL<DEV2:AMAX.RA
.R RALF
*DEV1:ATAN2.RL<DEV2:ATAN2.RA
.R RALF
*DEV1:SQRT.RL<DEV2:SQRT.RA
.R RALF
*DEV1:XFIX.RL<DEV2:XFIX.RA
.R RALF
*DEV1:ALOG10.RL<DEV2:ALOG10.RA
.R RALF
*DEV1:DIM.RL<DEV2:DIM.RA
.R RALF
*DEV1:EXPIR.RL<DEV2:EXPIR.RA
.R RALF
*DEV1:CHARS.RL<DEV2:CHARS.RA
.R RALF
*DEV1:DATE.RL<DEV2:DATE.RA
.R RALF
*DEV1:FLOAT.RL<DEV2:FLOAT.RA
/LINK THE LIBRARY:

.R LIBRA
*FORLIB.RL<DEV1:ABS,SIGN,AMIN,AMAX,DIM,EXP,EXP3,SIN,COS/C
*DEV1:TAN,TANH,SQRT,ASIN,ACOS,ATAN,FLOAT,CHARS,CHKEOF/C
*DEV1:ALOG10,DATE,ATAN2,IFIX,SINH,ALOG,COSH,AMOD,LTR/C
*,LPT:<DEV1:EXPII,RFCV,RFDV,PAUSE,EXPIR,XFIX,CLK8A,ONQIB

.DEL FORLIB.XX
.REN FORLIB.XX=FORLIB.RL
.DEL *.RL
.REN FORLIB.RL=FORLIB.XX

$END

