$JOB RX1FIN.BI: FINISH BUILDING RX02 V4 MEDIA.

$MSG IS A SECOND FLOPPY IN DRIVE 1? (^C TO ABORT)

.DUP RXA1:/S
.ZERO RXA1:

.COP RXA0:*.SV<*.V4
.DEL RXA0:F4.SV,PASS??.SV,LOAD.SV
.DEL RXA0:FRTS.SV,RALF.SV
.DEL RXA0:RTFLOP.SV,FUTIL.SV
.SQ RXA0:

.COP RXA0:<HELP.HL
.COP RXA0:<BASIC.OV,RESEQ.BA

.COP RXA1:<*.HN,FORLIB.RL
.COP RXA1:*.SV<F4.V4,PASS??.V4,LOAD.V4
.COP RXA1:*.SV<FRTS.V4,RALF.V4
.COP RXA1:*.SV<RTFLOP.V4,FUTIL.V4

/R CCL TO ACTIVATE V4
/SET TTY SCOPE
/SET SYS VT278 
/SET SYS INIT R LOG
.BO/RX
$END

