#!/usr/bin/perl

# A SIMH DECtape image is a set of 129 word DECtape blocks.
# Read in those blocks and write the first 128 words of each, 
# forming a series of 256 word blocks of an OS/8 file system.

open(INPUT, "mydt.tu56") || die "mydt.tu56: $!";
open(OUTPUT, ">myrk.dsk") || die "myrk.dsk: $!";
while (read(INPUT, $buf, 2*129) > 0) {
  syswrite(OUTPUT, $buf, 2*128);
}

exit 0;
