#!/usr/bin/perl
@rem = '
@echo off
c:\perl5\bin\perl %0 %1 %2 %3 %4 %5 %6 %7 %8 %9
goto endofperl
@rem ' if @rem;

#
@todo = @ARGV;
@todo = (".") unless @todo;

# open(STDOUT, ">vv.bat") || die "vv.bat: $!";
# print STDERR "Writing vv.bat...\n";

#
# Wander around finding directories named "Ok".
@Ok = (".");
while (@todo) {
last; # Just do "."
    $dir = shift @todo;
    opendir(DIR, $dir) || die "$dir: $!";
#   print STDERR "Reading '$dir' ...";
    foreach (readdir(DIR)) {
    	$f = "$dir/$_";
	next if $_ eq ".";
	next if $_ eq "..";
	next if $_ eq "done";
	next unless -d $f;
	if (/^[Oo][Kk]/) {
    print STDERR "pushing '$f' ...";
	    push(@Ok, $f);
	    next;
	}
	push(@todo, $f);
	next;
    }
#   print STDERR "\n";
    closedir(DIR);
}

#
# Process each file.
sub process {
    local($f) = @_;
    open(INPUT, $f) || die "$f: $!";
    $o = $f;
    $o =~ s/\.od$//;
    open(OUTPUT, ">$o") || die "$o: $!";
    binmode(OUTPUT);
    while (<INPUT>) {
        $byte = oct($_);
        $ch = pack("C", $byte);
	print OUTPUT $ch;
    }
    close(INPUT);
    close(OUTPUT) || die "$o: $!";
}

#
# For each directory named "Ok", process all the *.od files.
while (@Ok) {
    $dir = shift @Ok;
    opendir(DIR, $dir) || die "$dir: $!";
    print STDERR "Reading '$dir' ...";
    foreach (readdir(DIR)) {
    	$f = "$dir/$_";
	next unless -f $f;
	next unless /\.od$/;
	&process($f);
    }
    print STDERR "\n";
    closedir(DIR);
}


__END__
:endofperl
