#!/usr/bin/perl

#
# Find the binaries and such for a maindec.

$pwd = `pwd`; chop $pwd;
$pwd =~ s/\r//g;
die unless $pwd =~ /.*maindec-(..)-(.*)$/;
($p, $d) = ($1, $2);
foreach $f (<../../maindec/$p/$d*>) {
  $b = $f; $b =~ s:.*/::;
  system "cp $f maindec-$p-$b";
}
