$JOB TO COMPILE WHETSTONE SRC

.COMPILE WHET:<WHET:MAIN.FT/N
.COMPILE WHET:<WHET:MAINNT.FT/N
.COMPILE WHET:<WHET:P0.FT/N
.COMPILE WHET:<WHET:P3.FT/N
.COMPILE WHET:<WHET:PA.FT/N
.COMPILE WHET:<WHET:POUT.FT/N

.R LOAD
*WHET:WHET<WHET:MAIN,P0,P3,PA,POUT$
.R LOAD
*WHET:WHETNT<WHET:MAINNT,P0,P3,PA$

$END
