$JOB TO DELETE ADVENT STUFF
$RECONSTRUCTED BY VRS
.DEL A5TOA1.RA,A5TOA1.RL
.DEL ADVENT.DC,ADVENT.FT,ADVENT.LD,ADVENT.RL
.DEL BITSET.RA,BITSET.RL
.DEL BUG.FT,BUG.RL
.DEL CARRY.RA,CARRY.RL
.DEL CLEAR.BI,COMPIL.BI,LOAD.BI
.DEL DARK.RA,DARK.RL
.DEL DATA.DA
.DEL DECODE.RA,DECODE.RL
.DEL DROP.RA,DROP.RL
.DEL DSTROY.RA,DSTROY.RL
.DEL GETIN.FT,GETIN.RL
.DEL HERE.RA,HERE.RL
.DEL INITAD.FT,INITAD.RL
.DEL IO.FT,IO.RL
.DEL JUGGLE.RA,JUGGLE.RL
.DEL LIQLOC.RA,LIQLOC.RL
.DEL LIQ.RA,LIQ.RL
.DEL MOVE.RA,MOVE.RL
.DEL PCT.RA,PCT.RL
.DEL PSPEAK.RA,PSPEAK.RL
.DEL PUT.RA,PUT.RL
.DEL RKB.RA,RKB.RL
.DEL RND.FT,RND.RL
.DEL RSPEAK.RA,RSPEAK.RL
.DEL RUNAD.BI
.DEL SEED.RA,SEED.RL
.DEL SPEAK.RA,SPEAK.RL
.DEL TEXT.TX
.DEL TRVLOC.RA,TRVLOC.RL
.DEL VOCAB.RA,VOCAB.RL
.DEL YES.FT,YES.RL
$END
