<00
*3
D2/Q/ C2S/E./ B2/S/ A2/Q./ G1/E/ F1S/Q/ E1/Q/ D1/Q./ A2/E/ 
B2/Q./ B2/E/ C2S/Q./ C2S/E/ D2/Q./ D2/E/ D2/E/ C2S/E/ B2/E/ 
A2/E/ A2/E./ G1/S/ F1S/E/ D2/E/ D2/E/ C2S/E/ B2/E/ A2/E/ 
A2/E./ G1/S/ F1S/E/ *1
F1S/E/ F1S/E/ F1S/E/ F1S/E/ F1S/S/ G1/S/ 
A2/Q./ *2
G1/S/ F1S/S/ E1/E/ E1/E/ E1/E/ E1/S/ F1S/S/ G1/Q./ 
*3
F1S/S/ E1/S/ D1/E/ D2/Q/ B2/E/ A2/E./ G1/S/ F1S/E/ G1/E/ 
F1S/Q/ E1/Q/ D1/H/ D2/Q/ C2S/E./ B2/S/ A2/Q./ G1/E/ F1S/Q/ 
E1/Q/ D1/Q./ A2/E/ B2/Q./ B2/E/ C2S/Q./ C2S/E/ D2/Q./ D2/E/ 
D2/E/ C2S/E/ B2/E/ A2/E/ A2/E./ G1/S/ F1S/E/ D2/E/ D2/E/ 
C2S/E/ B2/E/ A2/E/ A2/E./ G1/S/ F1S/E/ *1
F1S/E/ F1S/E/ F1S/E/ 
F1S/E/ F1S/S/ G1/S/ A2/Q./ *2
G1/S/ F1S/S/ E1/E/ E1/E/ E1/E/ 
E1/S/ F1S/S/ G1/Q./ *3
F1S/S/ E1/S/ D1/E/ D2/Q/ B2/E/ A2/E./ 
G1/S/ F1S/E/ G1/E/ F1S/Q/ E1/Q/ D1/H/ D2/Q/ C2S/E./ B2/S/ 
A2/Q./ G1/E/ F1S/Q/ E1/Q/ D1/Q./ A2/E/ B2/Q./ B2/E/ C2S/Q./ 
C2S/E/ D2/Q./ D2/E/ D2/E/ C2S/E/ B2/E/ A2/E/ A2/E./ G1/S/ 
F1S/E/ D2/E/ D2/E/ C2S/E/ B2/E/ A2/E/ A2/E./ G1/S/ F1S/E/ 
*1
F1S/E/ F1S/E/ F1S/E/ F1S/E/ F1S/S/ G1/S/ A2/Q./ *2
G1/S/ F1S/S/ 
E1/E/ E1/E/ E1/E/ E1/S/ F1S/S/ G1/Q./ *3
F1S/S/ E1/S/ D1/E/ 
D2/Q/ B2/E/ A2/E./ G1/S/ F1S/E/ G1/E/ F1S/H/ E1/H/ D1/H..../ 
>00 $
