#!/usr/bin/perl

#
# Parse the file a line at a time and decide whether to copy the line
# or elide it.
%symbols = ();	# Start with an empty symbol table
foreach $file (@ARGV) {
  $file =~ y/a-z/A-Z/;
  if ($file =~ /-D(.*)/) {
    $symbols{$1} = 1;
  } else {
    open(INPUT, $file) || die "$file: $!";
    last;
  }
}
open(STDOUT, ">perlpp.out") || die "perlpp.out: $!";
$output = 1;	# Start with output enabled
$line = 0;	# No lines yet
$nest = 0;	# Not nested yet
while (<INPUT>) {
  $line++;
  if (/^#/) {
    y/a-z/A-Z/;
    /^#\W*([A-Z]+)\W+(([A-Z0-9]+))*/;
    if ($1 eq 'DEFINE') {
      $symbols{$2} = 1;
      next;
    } elsif ($1 eq 'UNDEF') {
      $symbols{$2} = undef;
      next;
    } elsif ($1 eq 'IFDEF') {
      $output-- unless defined $symbols{$2};
      $nest++;
      next;
    } elsif ($1 eq 'IFNDEF') {
      $output-- if defined $symbols{$2};
      $nest++;
      next;
    } elsif ($1 eq 'ELSE') {
      next if $output < 0; # Ignore nested else
      $output = !$output; # Toggle if not nested
      next;
    } elsif ($1 eq 'ENDIF') {
      $nest--;
      $output++ unless $output > 0;
      die "Unmatched endif at line $line" if $nest < 0;
      next;
    }
    die "Unknown directive: '$1' at line $line";
  } else {
    print if $output > 0;
  }
}

__END__
:endofperl
