<00
*3
^A2/S/ ^A2/S/ ^G1S/S/ ^G1S/S/ ^G1/S/ ^G1/S/ ^F1S/S/ ^F1S/S/ ^F1/S/ 
^F1/S/ ^E1/S/ ^E1/S/ ^D1S/S/ ^D1S/S/ ^D1/S/ ^D1/S/ ^C1S/S/ ^C1S/S/ 
^C1/S/ ^C1/S/ ^B1/S/ ^B1/S/ ^A1S/S/ ^A1S/S/ ^A1/S/ ^A1/S/ A1/E/ 
E1/E/ C1/E/ E1/E/ A1/E/ E1/E/ C1/E/ E1/E/ A1/E/ E1/E/ 
C1/E/ E1/E/ A1/E/ E1/E/ C1/E/ E1/E/ A1/E/ E1/E/ C1/E/ 
E1/E/ A1/E/ E1/E/ C1/E/ E1/E/ A1/E/ E1/E/ C1/E/ E1/E/ 
A1/E/ E1/E/ C1/E/ E1/E/ B1/Q/ D1/Q/ E1/Q/ D1/E/ E1/E/ 
F1S/E/ E1/E/ D1/E/ E1/E/ *0
A1/E/ *3
F1S/Q/ E1/E/ F1S/Q/ E1/Q/ 
D1/E/ E1/E/ D1/E/ B1/W../ E1/Q/ G1/Q/ A2/Q/ G1/E/ A2/E/ 
B2/E/ A2/E/ G1/E/ A2/E/ *0
A1/E/ *3
B2/Q/ A2/E/ B2/Q/ A2/Q/ 
G1/E/ A2/E/ G1/E/ E1/W../ F1S/Q/ D1S/E/ F1S/Q./ D1S/E/ F1S/E/ 
G1/Q/ E1/E/ F1S/Q/ E1/E/ F1S/E/ E1/E/ F1S/Q/ D1S/E/ F1S/Q/ 
D1S/E/ F1S/E/ G1/Q/ E1/E/ F1S/Q/ E1/E/ F1S/E/ E1/E/ F1S/Q/ 
E1/E/ F1S/Q/ E1/E/ F1S/E/ E1/E/ F1S/Q/ E1/E/ F1S/Q/ E1/E/ 
F1S/E/ E1/E/ A2/W..../ B1/Q/ D1/Q/ E1/Q/ D1/E/ E1/E/ F1S/E/ 
E1/E/ D1/E/ E1/E/ *0
A1/E/ *3
F1S/Q/ E1/E/ F1S/Q/ E1/Q/ D1/E/ 
E1/E/ D1/E/ B1/W../ E1/Q/ G1/Q/ A2/Q/ G1/E/ A2/E/ B2/E/ 
A2/E/ G1/E/ A2/E/ *0
A1/E/ *3
B2/Q/ A2/E/ B2/Q/ A2/Q/ G1/E/ 
A2/E/ G1/E/ E1/W../ F1S/Q/ D1S/E/ F1S/Q./ D1S/E/ F1S/E/ G1/Q/ 
E1/E/ F1S/Q/ E1/E/ F1S/E/ E1/E/ F1S/Q/ D1S/E/ F1S/Q/ D1S/E/ 
F1S/E/ G1/Q/ E1/E/ F1S/Q/ E1/E/ F1S/E/ E1/E/ F1S/Q/ E1/E/ 
F1S/Q/ E1/E/ F1S/E/ E1/E/ F1S/Q/ E1/E/ F1S/Q/ E1/E/ F1S/E/ 
E1/E/ A2/Q/ A2/Q/ A2/H/ A2/Q/ A2/E/ C2/Q/ C2/E/ B2/E/ 
A2/E/ B1/Q/ D1/Q/ E1/Q/ D1/E/ E1/E/ F1S/E/ E1/E/ D1/E/ 
E1/E/ *0
A1/E/ *3
F1S/Q/ E1/E/ F1S/Q/ E1/Q/ D1/E/ E1/E/ D1/E/ 
B1/W../ E1/Q/ G1/Q/ A2/Q/ G1/E/ A2/E/ B2/E/ A2/E/ G1/E/ 
A2/E/ *0
A1/E/ *3
B2/Q/ A2/E/ B2/Q/ A2/Q/ G1/E/ A2/E/ G1/E/ 
E1/W../ F1S/Q/ D1S/E/ F1S/Q./ D1S/E/ F1S/E/ G1/Q/ E1/E/ F1S/Q/ 
E1/E/ F1S/E/ E1/E/ F1S/Q/ D1S/E/ F1S/Q/ D1S/E/ F1S/E/ G1/Q/ 
E1/E/ F1S/Q/ E1/E/ F1S/E/ E1/E/ F1S/Q/ E1/E/ F1S/Q/ E1/E/ 
F1S/E/ E1/E/ F1S/Q/ E1/E/ F1S/Q/ E1/E/ F1S/E/ E1/E/ A2/W..../ 
^A2/S/ ^A2/S/ ^G1S/S/ ^G1S/S/ ^G1/S/ ^G1/S/ ^F1S/S/ ^F1S/S/ ^F1/S/ 
^F1/S/ ^E1/S/ ^E1/S/ ^D1S/S/ ^D1S/S/ ^D1/S/ ^D1/S/ ^C1S/S/ ^C1S/S/ 
^C1/S/ ^C1/S/ ^B1/S/ ^B1/S/ ^A1S/S/ ^A1S/S/ ^A1/S/ ^A1/S/ A1/Q./ 
*0
A1/Q/ *3
G1/E/ B2/E/ E2/W./ B2/Q/ G1/Q/ G1/H/ G1/Q/ B2/E/ 
D2/Q/ B2/E/ A2/E/ G1/E/ A2/Q/ F1/Q/ F1/H/ F1/Q/ A2/E/ 
C2/Q/ C2/E/ B2/E/ A2/E/ B2/Q/ G1/E/ G1/H/ G1/Q/ B2/E/ 
D2/Q/ D2/E/ C2/E/ B2/E/ C2/Q/ A2/Q/ A2/H/ A2/Q/ C2/E/ 
E2/Q/ C2/E/ B2/E/ A2/E/ B2/Q/ G1/Q/ G1/H/ G1/Q/ B2/E/ 
D2/Q/ B2/E/ A2/E/ G1/E/ A2/Q/ F1/Q/ F1/H/ F1/Q/ A2/E/ 
C2/Q/ A2/E/ G1/E/ F1/E/ E1/W..../ A1/E/ E1/E/ C1/E/ E1/E/ 
A1/E/ E1/E/ C1/E/ E1/E/ *2
A1/E/ E1/E/ C1/E/ E1/E/ A1/E/ 
E1/E/ C1/E/ E1/E/ *1
A1/E/ E1/E/ C1/E/ E1/E/ A1/E/ E1/E/ 
C1/E/ E1/E/ 
>00 $
