<00
*3
B2/Q/ A2/E/ G1/Q/ E1/E/ F1S/E/ G1/E/ F1S/E/ E1/Q./ B2/Q/ 
A2/E/ G1/Q/ E1/E/ F1S/E/ G1/E/ F1S/E/ E1/Q./ G1/Q/ G1/E/ 
A2/Q/ A2/E/ B2/Q/ B2/E/ D2/E/ C2/E/ B2/E/ A2/E/ B2/E/ 
A2/E/ G1/Q/ F1S/E/ E1/Q./ F1S/Q/ A2/E/ G1/Q/ G1/E/ G1/Q/ 
D1/E/ G1/Q/ E1/E/ G1/Q/ *0
A1/E/ *3
G1/Q/ G1/E/ G1/Q/ D1/E/ 
G1/Q/ E1/E/ G1/Q./ G1/Q/ G1/E/ A2/Q/ B2/E/ C2/Q/ B2/E/ 
A2/Q/ B2/E/ G1/Q/ G1/E/ G1/Q/ D1/E/ G1/Q/ E1/E/ G1/Q./ 
B2/Q/ A2/E/ G1/Q/ E1/E/ F1S/E/ G1/E/ F1S/E/ E1/Q./ B2/Q/ 
A2/E/ G1/Q/ E1/E/ F1S/E/ G1/E/ F1S/E/ E1/Q./ G1/Q/ G1/E/ 
A2/Q/ A2/E/ B2/Q/ B2/E/ D2/E/ C2/E/ B2/E/ A2/E/ B2/E/ 
A2/E/ G1/Q/ F1S/E/ E1/Q./ F1S/Q/ A2/E/ G1/Q/ G1/E/ G1/Q/ 
D1/E/ G1/Q/ E1/E/ G1/Q/ *0
A1/E/ *3
G1/Q/ G1/E/ G1/Q/ D1/E/ 
G1/Q/ E1/E/ G1/Q./ G1/Q/ G1/E/ A2/Q/ B2/E/ C2/Q/ B2/E/ 
A2/Q/ B2/E/ G1/Q/ G1/E/ G1/Q/ D1/E/ G1/Q/ E1/E/ G1/Q./ 
B2/Q/ A2/E/ G1/Q/ E1/E/ F1S/E/ G1/E/ F1S/E/ E1/Q./ B2/Q/ 
A2/E/ G1/Q/ E1/E/ F1S/E/ G1/E/ F1S/E/ E1/Q./ G1/Q/ G1/E/ 
A2/Q/ A2/E/ B2/Q/ B2/E/ D2/E/ C2/E/ B2/E/ A2/E/ B2/E/ 
A2/E/ G1/Q/ F1S/E/ E1/Q./ F1S/Q/ A2/E/ G1/Q/ G1/E/ G1/Q/ 
D1/E/ G1/Q/ E1/E/ G1/Q/ *0
A1/E/ *3
G1/Q/ G1/E/ G1/Q/ D1/E/ 
G1/Q/ E1/E/ G1/Q./ G1/Q/ G1/E/ A2/Q/ B2/E/ C2/Q/ B2/E/ 
A2/Q/ B2/E/ G1/Q/ G1/E/ G1/Q/ *2
D1/E/ G1/Q/ *1
E1/E/ G1/Q./ 
>00 $
