<00
*3
E1/E/ A2/Q/ C2/E/ E2/Q/ C2/Q/ E2/Q/ D2/E./ C2/S/ B2/E./ 
C2/S/ B2/E./ A2/S/ G1/Q/ E1/E/ A2/Q./ E1/Q/ G1/E./ A2/S/ 
G1/E/ F1/H.../ G1/E./ A2/S/ B2/Q/ C2/Q/ D2/Q/ E2/Q/ E2/Q/ 
E2/Q/ E2/Q/ E2/Q./ A2/E/ E2/E./ F2/S/ C2S/Q/ D2/H..../ *0
A1/Q./ 
*3
G1/E/ D2/E./ C2/S/ B2/Q/ C2/Q/ *2
B2/Q/ C2/Q/ *0
A1/Q/ *2
E1/E./ 
G1S/S/ B2/E/ D2/Q./ *0
A1/Q/ *3
E1/E/ A2/Q/ C2/E/ E2/Q/ C2/Q/ 
E2/Q/ D2/E./ C2/S/ B2/E./ C2/S/ B2/E./ A2/S/ G1/Q/ E1/E/ 
A2/Q./ E1/Q/ G1/E./ A2/S/ G1/E/ F1/H.../ G1/E./ A2/S/ B2/Q/ 
C2/Q/ D2/Q/ E2/Q/ E2/Q/ E2/Q/ E2/Q/ E2/Q./ A2/E/ E2/E./ 
F2/S/ C2S/Q/ D2/H..../ *0
A1/Q./ *3
G1/E/ D2/E./ C2/S/ B2/Q/ C2/Q/ 
*2
B2/Q/ C2/Q/ *0
A1/Q/ *3
^G1S/Q/ ^A2/Q/ ^B2/H/ ^A2/H/ ^B2/H/ ^C2/Q/ 
^B2/Q/ ^A2/H/ ^C2/Q/ ^B2/Q/ ^A2/H/ ^A2/H..../ ^A2/H..../ ^A2/H..../ ^E1/Q/ 
^D1/Q/ ^E1/Q/ ^F1/Q/ ^G1/H..../ E1/E/ A2/Q/ C2/E/ E2/Q/ C2/Q/ 
E2/Q/ D2/E./ C2/S/ B2/E./ C2/S/ B2/E./ A2/S/ G1/Q/ E1/E/ 
A2/Q./ E1/Q/ G1/E./ A2/S/ G1/E/ F1/H.../ G1/E./ A2/S/ B2/Q/ 
C2/Q/ D2/Q/ E2/Q/ E2/Q/ E2/Q/ E2/Q/ E2/Q./ A2/E/ E2/E./ 
F2/S/ C2S/Q/ D2/H..../ *0
A1/Q./ *3
G1/E/ D2/E./ C2/S/ B2/Q/ C2/Q/ 
*2
B2/Q/ C2/Q/ *0
A1/Q/ *3
A2/E/ E2/E./ F2/S/ C2S/Q/ D2/H..../ *0
A1/Q./ 
*3
G1/E/ D2/E./ C2/S/ B2/Q/ C2/Q/ *2
B2/Q/ C2/Q/ *0
A1/Q/ *3
^G1S/Q/ 
^A2/Q/ ^B2/H/ ^A2/H/ ^B2/H/ ^C2/Q/ ^B2/Q/ ^A2/H/ ^C2/Q/ ^B2/Q/ 
^A2/H/ ^A2/H..../ ^A2/H..../ ^A2/H..../ ^E1/Q/ ^D1/Q/ ^E1/Q/ ^F1/Q/ ^G1/H..../ 
*2
E1/E./ G1S/S/ B2/E/ D2/Q./ *0
A1/Q/ *3
E1/E/ A2/Q/ C2/E/ E2/Q/ 
C2/Q/ E2/Q/ D2/E./ C2/S/ B2/E./ C2/S/ B2/E./ A2/S/ G1/Q/ 
E1/E/ A2/Q./ E1/Q/ G1/E./ A2/S/ G1/E/ F1/H.../ G1/E./ A2/S/ 
B2/Q/ C2/Q/ D2/Q/ E2/Q/ E2/Q/ E2/Q/ E2/Q/ E2/Q./ A2/E/ 
E2/E./ F2/S/ C2S/Q/ D2/H..../ *0
A1/Q./ *3
G1/E/ D2/E./ C2/S/ B2/Q/ 
C2/Q/ *2
B2/Q/ C2/Q/ *0
A1/Q/ *3
A2/E/ E2/E./ F2/S/ C2S/Q/ D2/H..../ 
*0
A1/Q./ *3
G1/E/ D2/E./ C2/S/ B2/Q/ C2/Q/ *2
B2/Q/ C2/Q/ *0
A1/Q/ 
*3
A2/E/ E2/E./ F2/S/ C2S/Q/ D2/H..../ *0
A1/Q./ *3
G1/E/ D2/E./ C2/S/ 
B2/Q/ C2/Q/ *2
B2/Q/ C2/H..../ 
>00 $
