$JOB          PRODUCE ALL CREF LISTINGS FOR RTOS
.PAL QS8SUP,QS8SUP<QS8PAR,OS8Q8,QTASK3/J/C
.PAL RTS8,RTS8<QS8PAR,RTS8/J/C
.PAL CLOCK,CLOCK<QS8PAR,CLOCK/J/C
.PAL MCR,MCR<QS8PAR,MCR/J/C
.PAL TTY,TTY<QS8PAR,TTY/J/C
.PAL RK8E,RK8E<QS8PAR,RK8E/J/C
.PAL LTA,LTA<QS8PAR,LTA/J/C
.PAL USER1,USER1<QS8PAR,USER1/J/C
.PAL USER2,USER2<QS8PAR,USER2/J/C
$END
