#!/usr/bin/perl

#PDP-12 PROGRAM ABSTRACTS
$catalog = "July 1974";

$heredoc = <<'HEREDOC';
DECUS NO. 12-40
PDP-8 Disk Monitor - LAP6-DIAL Interface
John R. Raines, Northwestern University Medical School,
Chicago, Illinois
This package contains three programs which facilitate operation
of the PDP~8 Disk Monitor and LAP6-DIAL operating systems
on a PDP-12 at the same time. Rapid bidirectional ASCII and
binary file communication between the two operating systems
is also provided for.
Minimum Hardware:	PDP-12A, DF32 Disk, 8K, TTY,
			VC 12 Display
Source Language:	DIAL

DECUS NO. 12-41
BLOOPD - Blood Pressure Display Program
Julia A. Voland
Submitted by: Dr. Nelson E. Leatherman, Indiana University,
Bloomington, Indiana
BLOOPD is primarily for visual information only. It displays
either the blood pressure waveform on a calibrated scope, or
the digitized values of four parameters of the blood pressure.
A printout of the values is also provided. All options are
selected by teletype.
Minimum Hardware:	PDP-12A
Storage Requirement:	Two fields, total 2713(8) locations
Source Language:	LAP6

DECUS NO. 12-42
CALCO 12
Richard Reeder, State University of New York, Stony Brook, New York
This plotter program can be used with programs like CATACAL
to obtain reasonably high-speed hard copy of data which is
stored on tape.
Minimum Hardware:	PDP-12, Model 565 CalComp
			Plotter, VR12 Display, One
			LINCtape Unit, EAE
Storage Requirement:	1K of core
Source Language:	DIAL

DECUS NO. 12-43
PLOT3D
J. Cohen and M. Carhart,
Northwestern University Medical School, Chicago, Illinois
This program displays data from LINCtape and allows for user
modification before plotting on an XY plotter. As each block
is plotted, the previous data is not overwritten. This produces
a three-dimensional effect. Data can be single or
double precision. The space between each block is selectable.
A subroutine to label each graph is included. Frequency power
spectra data shows time shifts.
Minimum Hardware:	4K PDP-12, XYr Plotter
Storage Requirement:	4K
Source Language:	LAP6-DIAL

DECUS NO. 12-44
AVERDT
J. Cohen and M. Carhart,
Northwestern University School of Medicine, Chicago, Illinois
This program is designed for averaging EEG analog data points
with delayed trigger to indicate each epoch In this way data
both before and after the signal can be studied. The epoch
length can vary from 1 to 7 seconds and 7 data channels are
available. A number of trials are averaged and can be displayed
and saved on LINCtape.  One can select a variable
stimulus probe. This program is excellent for measuring
readiness potentials.
Minimum Hardware:	8K PDP-12, KW12
Source Language:	LAP6-DIAL

DECUS NO. 12-45
FOCALP - FOCALPE
Judson Gilbert, Florida State University, Tallahassee, Florida
This is a new version of FOCAL 5/69 (DECUS NO. FOCAL8-52)
which has been tailored to the 4K PDP-12A with an incremental
plotter. Theprogram exists as symbolic and binary
programs on a DIAL V2 tape. In this way it can be readily
modified/reassembled/and loaded. There are two versions --
FOCALPE with extended functions, FOCALP without. Many
of the commands and features have been changed in this
program.
Minimum Hardware:	4K PDP-I 2A, Incremental Plotter
Source Language:	DIAL

DECUS NO. 12-46
STRINGS
John R. Raines, Northwestern University Medical School,
Chicago, Illinois
This program provides a character string search function to the
DIAL-MS editor. Any character string up to 15 characters in
length may be searched for in the work area of the DIAL-MS
editor, using STRINGS.
Minimum Hardware:	8K PDP-12B
Other Programs Needed:	DIAL-MS
Restrictions:		Will not run under DIAL-V2
Source Language:	DIAL

DECUS NO. 12-47
PIP-1600
John R. Raines, Northwestern University Medical School,
Chicago, Illinois
This program is useful in conjunction with DIAL-MS tapes
using DEC's new LINCtape format of 1600 blocks. It provides
facilities for storing and retrieving source and binary
files on these tapes (existing software would not store above
block 778(8)). Also provided is an option to duplicate entire
(1600(8) block) LINCtapes. PIP-1600 can reference the DIAL-MS
work area for either source mode input or output. PIP-1600
effectively doubles the storage area on DIAL LINCtapes.
Minimum Hardware:	8K PDP-12B
Other Programs Needed:	DIAL-MS, MARK 12-l (Included
			on LINCtape)
Restrictions:		Will not run under DIAL-V2
Source Language:	DIAL

DECUS NO. 12-48
PS/8 FORTRAN Library Routines
Charles M. Moore, III, Rice University, Houston, Texas
This package contains a set of additional PS/8 FORTRAN
Library routines. The binary files containing these routines
have been collected into library file LIB12.RL on the
LINCtape. A modified version of LOADER.SV is provided which
searches both LIB12 and LIB8 when completing the building
of a core image of a user's program. File WRITE.UP provides
additional details. FORTRAN demonstration programs are
included on tape.</div>
<div>Among the routines included on the LINCtape are:</div>
<div>1. PDP-12 PS/8 FORTRAN Display Routines</div>
<div>2. PS/8 FORTRAN Teletype I/O Routines</div>
<div>3. PS/8 FORTRAN File l/O Routines</div>
<div>4. PDP-12 PS/8 FORTRAN LINC mode l/O Routines</div>
<div>5. PDP-12 PS/8 FORTRAN LINCtape l/O Routines
Minimum Hardware:	PDP-12 with PS/8 (Some will run
			on PDP-8 with PS/8). Display
			routines require CRT and some
			require EAE. Two routines require
			KW12-A real-time clock
Miscellaneous:		Entire package is contained on a
			PDP-12 LINCtape marked using
			128-word blocks
Source Language:	SABR

DECUS NO. 12-49
Cold Start DF32 Disk Formatter for PS/8 on a PDP-12
Mario DeNobili
Submitted by: Stanley Rabinowitz,
Digital Equipment Corporation, Maynard, Massachusetts
The following problem arises for users who have a PDP-12
(with LINCtape) and a DF32 disk and who wish to use the
PS/8 programming system:
They would like to use the disk as the system device since
this expands the capabilities of PS/8 and speeds it up consid-
erably; however, they cannot devote the disk to the exclusive
use of PS/8 since other programs (notably the LAP6-DIAL-MS
monitor system) require the use of the disk. Recreating the
PS/8 disk system from scratch is normally very time consuming.
This-document explains a method for the user to create a PS/8
disk system from scratch as easily as he can bootstrap into a
PS/8 LINCtape system.
Minimum Hardware:	8K PDP-12B, 32KDF32 Disk,
			LINCtape
Other Programs Needed:	PS/8-8K Programming System,
			PS/8 Configurator
Storage Requirement:	4000-4260
Source Language:	Assembly Language

DECUS NO. 12-50
EDIT-12
Henry A. Maurer, Digital Equipment Corporation, Maynard,
Massachusetts
EDIT-12 is a simple modification of PS/8's EDIT that causes
all characters to appear on the scope instead of on the teletype,
considerably speeding up editing.
Minimum Hardware:	Any PS/8 configuration on a PDP-12
Source Language:	PAL-8

DECUS NO. 12-51
MAGSPYD
Clark S. Donley, Johns Hopkins University, Baltimore,
Maryland
MAGSPYD is a modification of MAGSPY that provides the
ability to look at any length tape, and to view the unpacked
ASCII generated by the DIAL-MS assembler with a LISTAPE
instruction. It allows convenient use of the teletype to restart
the program, rewind the tape, go to DIAL, or to display a
HELP frame to explain the sense switch options. It includes
an A/D knob to control the number of lines displayed on the
screen and a sense switch option to stop the movement of the
display. It also contains the octal display and large/small
waveform options of earlier modifications.
Minimum Hardware:	4K PDP-12
Source Language:	LAP6-DIAL

DECUS NO. 12-52
Student Test Analysis
Stephen J. Mayor, Ph.D., Medical College of Ohio at Toledo,
Toledo, Ohio
This is a three-part program to score and do item analysis of
student responses. Part I of the program scores parts of the
exam. It prints out the student's number and his score on that
part of the exam along with the percentage of the class making
the correct answer. Part II takes the scores of all parts of the
exam and prints out: (1) the student's number and his overall
score, (2) the class mean and standard deviation, (3) the
decile distribution in terms of percentage of class, (4) a plot
of the decile distribution. Part III of the program computes
the distribution of answers, in terms of percentage of class,
to a given question for each part of the exam. Printout is
(1) question number, (2) choice number, (3) % of class making
that choice, (4) answer key.
Minimum Hardware:	4K PDP-12
Source Language:	FOCAL-4K

DECUS NO. 12-53
Liquid Scintillation Counting: Conversion of CPM to DPM in
Double-label Experiments
Stephen J. Mayor, Ph. D, Medical College of Ohio at Toledo,
Toledo, Ohio
This program takes the raw data outputted from the LSC's
(Packard Model 3380) teletype punch, and using the Okitz
equations, calculates the DPM for two isotopes of each
sample. The AES ratio is used to calculate percentage of
efficiency and spillover for each isotope.
Minimum Hardware:	PDP-12A, Teletype punch and
			reader
Storage Requirement:	4096 words
Source Language:	FOCAL-4K

DECUS NO. 12-54
QUIP - Quick Assembler for the PDP-12
Stephen G._Wellcome, Digital Equipment Corporation,
Maynard, Massachusetts
QUIP is a modification of the DEC Floating Point Assembler
to enable it to handle LMODE as well as PMODE instructions.
All of the floating point handlers have been removed, and in
their place have been substituted handlers for LINC code,
ring buffer handlers and nopause routines. Because both the
LMODE and PMODE symbol tables are core resident and
because of the symbol table search algorithm used, operation
is up to four times faster than the DIAL Assembler.
Minimum Hardware:	8K PDP-12
Other Programs Needed:	DIAL-MS I/O Routines
Source Language:	DIAL

DECUS NO. 12-55
FFAESIM
H. G. Helgeson, Forsvarets Forskningsanstalt, Stockholm,
Sweden
This program makes it possible to runthe FFTD program on a
PDP-12 without the EAE option. It consists of a modified
version of Digital-8-17-U, Extended Arithmetic Element
Instruction Set Simulator, and a patch to change the EAE
instructions in FFTD.
Minimum Hardware:	8K PDP-12B
Other Programs Needed:	FFTD (DEC-12-FQEA)
Storage Requirement:	165-177; 200-357; 1600-1653
Source Language:	LAP6-DIAL

DECUS NO. 12-56
QANDA+ - Modified QANDA Subroutine
W. R. J. Funnell, McGill University, Montreal, Canada
QANDA+ is a modified version of the QANDA subroutine
(DEC-12-FISA). The following changes have been made:
(1) it no longer needs to be in the same instruction field as
the calling program, (2) both QANDA itself, and the
GETKBD subroutine, return control to LAP6-DIAL when
Cntrl/D is typed, (3) the routines for returning to LAP6-DIAL,
and for typing a carriage return/line feed pair, are both
accessible to external programs, and (4) the calling sequence
has been changed.
Minimum Hardware:	PDP-12B
Storage Requirement:	First 4 pages of any segment
Restrictions:		Same as for QANDA, also , TTY
			must be initialized before use
Source Language:	LAP6-DIAL

DECUS NO. 12-57
SPY+ - Modified MAGSPY
W. R. J. Funnell, McGill University, Montreal, Canada
SPY+ is a modified version of MAGSPY (DEC-12-USZA). It
incorporates the added features of DECUS NO. 12-21 (by
Lawrence Moss), as well as the following features: (1) it can
handle tapes marked with 1600(8) blocks, (2) upon reaching the
end of the tape it will stop moving the window, rather than go
to the other end of the tape, (3) it is controlled from the TTY
rather than from the sense switches, and (4) the waveform
display may be scaled by means of knob 0.
Minimum Hardware:	PDP-12A
Storage Requirement:	All of segment 1, 6 pages in
			segment 2, 4 pages in segment 3
Source Language:	LAP6-DIAL

DECUS NO. 12-58
FIFOCON
Gerald W. Dulaney, Digital Equipment Corporation, Maynard,
Massachusetts
FIFOCON is a File Format Converter program to transfer
integer fraction or floating point format data files into any of
those formats. Input can be by block number or filename,
output is in DIAL file format and can handle double precision
integer input or output.
Minimum Hardware:	PDP-12/30 (8K, LINCtape, etc.)
Other Programs Needed:	FOCAL-12, DIAL-MS
Source Language:	FOCAL-12

DECUS NO. 12-59
FOCPLOT
R. Thomas Divers, Case Western Reserve University,
Cleveland, Ohio
FOCPLOT is an interactive program to plot FOCAL-12
generated data from integer tape files to a digital plotter.
Annotation symbols can be superimposed on the data. Point
plot or continuous (straight line between adjacent points)
curves may be specified. A short overlay is provided to
permit annotated axes and a legend.
Minimum Hardware:	8K PDP-12, LINCtape, Digital
			Plotter (CalComp or equivalent)
			VR-12, TTY
Other Programs Needed:	DECUS NO. 8-168, QANDA
			(both incorporated), LAP-6,
			DIAL-MS
Storage Requirement:	100-153, 2400-11665
Restrictions:		Maximum of 767 points can be
			plotted
Source Language:	LAP-6, DIAL-MS

DECUS NO. 12-60
SUMER (French)
J. F. Champarnaudand F. H. Bostem, Liege, Belgium
This French language version of HAMURABI (The Sumer Game,
FOCAL8-5) is available on both paper tape and PDP-12
LINCtape.  On the LINCtape, both FOCAL, 8K and FOCAL
SUMER lists are included.
Minimum Hardware:	8K PDP-8 or PDP-12
Source Language:	8K FOCAL '69

DECUS NO. 12-61
Generating Random Numbers with FOCAL
W. Siegel, K. Whittle and J. Siegel,
University of Western Ontario, London, Canada
This program provides a patch to correct the problem with
FOCAL's random number generator. This routine was an
algorithm developed by Green, Smith and Klem (1959) which
has several advantages for use with minicomputers. First,
unlike most such generators, it uses an addative rather than a
multiplicative process; addition is much faster than multiplication
with most machines. Second, the routine is relatively
short and third, it has been documented and tested and its
characteristics are known. A listing for the patch for FOCAL-12
is provided, but other versions of FOCAL may be modified
with similar changes. Three short general programs are included
which type out sequences of random integers.
Minimum Hardware:	PDP-8 or PDP-12
Other Programs Needed:	FOCAL, FOCAL-12
Source Language:	Assembly Language

DECUS NO. 12-62
RUFUS
David M. Stern,
Laboratory for Atmospheric and Space Physics,
University of Colorado, Boulder, Colorado
RUFUS is a display-oriented programmable spectral analysis
system. Basic data structures are 512 point vectors which are
stored in 6 registers in memory. These registers may be
manipulated by a powerful set of commands.
Minimum Hardware:	8K PDP-12/30, 2 LINCtape
			drives (KW12A real time clock,
			CALcomp 565 plotter, card
			reader and LP-8 line printer
			optional)
Storage Requirement:	8K and overlay storage on
			LINCtape
Source Language:	PAL

DECUS NO. 12-63
OLFFT1 and FETCHFFT (See also DECUS NO. 12-144)
R. Cooper, P. V. Pocock, W. J. Warren,
Burden Neurological Institute, Stapleton, Bristol, England
OLFFT1 will analyze (continuously or non-continuously) time
series data into power spectra using the Fast Fourier Transform
and store the spectra on LINCtape.
<P>
FETCHFFT will retrieve Spectra stored by OLFFT1 for further
inspection including, displaying and plotting.
Minimum Hardware:	PDP-12/30, 8k memory; KW12A
			Real Time Clock; A/D converters
Source Language:	DIAL

DECUS NO. 12-64
Walsh Transform Subroutines, PWALSH and LWALSH
Major Tom G. Purnhagen, Air Force Institute of Technology,
Wright Patterson Air Force Base, Ohio
PWALSH and LWALSH are PDP-12 subroutines, written in
PDP-8 mode and LINCmode respectively, which compute the
"natural" Walsh transform of an N=2^K element array of data.
As listed, the programs operate on an array of 256 points
(K=8). Modification for different values of K is described in
the program write-up.
Minimum Hardware:	PWALSH: Any PDP-8 or PDP-12;
			LWALSH: Any PDP-12
Storage Requirement:	50-54 Locations, plus data and
			work area
Source Language:	LAP-6/DIAL (PWALSH is com-patible
			with PAL III

DECUS NO. 12-65
PISH- Poststimulus Time and Interspike - Interval Histogram
Dr. D. J. Woodward, University of Rochester
Submitted by: Ron Carter, Digital Equipment Corporation,
Maynard, Massachusetts
PISH consists of two programs, ISH (interspike interval
histogram) and PSTH (poststimulus time histogram). ISH and PSTH
compute density histograms of the frequency of time intervals
between events or of frequency of events after synchronizing
or stimulating pulses. The programs are capable of analyzing
times of occurrence of single events and of groups of events
defined as bursts.
Minimum Hardware:	8K PDP-12, KW12A, LINCtapes
Source Language:	DIAL

DECUS NO. 12-66
ADDINDX (LAP6-DIAL-MS Index Manipulator)
Rager C. Tindle, U. S. Dept. of Interior,
Fish-Pesticide Research Laboratory, Columbia, Missouri
ADDINDX allows the user to enter, delete or search for
programs in the DIAL index. The major value of the pragram is
that new entries maybe specified in the tape area above Blk
777. The program is essentially a handler for the subroutine
set MILDRED. QANDA is used for the display frames.
Minimum Hardware:	8K PDP-12/20; supports multiple
			tape units and RK8 or RS08 disk
Other Programs Needed:	QANDA (DEC-12-FISA),
			MILDRED (DEC-12-FZDA),
			uses DIAL-MS I/O routines.
Restrictions:		A DIAL-MS System tape must be
			mounted on unit 0
Source Language:	LAP6-DIAL-MS

DECUS NO. 12-67
PPG FOCAL
Edward Steinfeld
Submitted by: Karen Seefeldt, Digital Equipment Corporation,
Pittsburgh, Pennsylvania
PPGFOCAL is a modification of DECUS NO. 12-24. It
combines the overlays \$DEVICE, \$CHARS12 and \$DTOA.
The functions FATN, FCOS, FSIN, FEXP and, FLOG have
been removed. The System does not check for a negative sign
when doing a square root. PPGFOCAL has room for approximately
200 variables.
Minimum Hardware:	12K PDP-12
Source Language:	LAP6-DIAL


DECUS NO. 12-68
A PDP-8 Floating Point Software Package Simulator Using a
FPP-12 Floating Point Processor
L. G. Boxall and R. H. Abel, Colorado State University,
Fort Collins, Colorado
This FPP-12 simulator can be used to directly replace the
floating point software package in any PDP-12 assembler
program. Enhanced computational speed (5 to 10 times) and
smaller core requirements are realized by the use of the FPP
simulator. The simulator will accept all of the instructions
used in the PDP-8 floating point systems packages, as well as
providing many additional programming features.
Minimum Hardware:	PDP-12, FPP-12 Processor
Storage Requirement:	0.7K plus optional routines
Restrictions:		Must be located in field 0
Source Language:	Assembler-PDP and FPP-12

DECUS NO. 12-69
An On-Line FOCAL-12 Program for Auto-Analyzers
Mack W. Overton, Jr., Larry L. Alber and Dr. Donald E. Smith,
U. S. Food and Drug Administration, Chicago, Illinois
This is a pragram for auto-analyzer data acquisition and
reduction on a mini-computer, using an easily constructed
interface. Circuit diagrams for the interface are included
with the program write-up.
Minimum Hardware:	PDP-12/30 or PDP-12/20 with
			KW12A clock and 8K core
Source Language:	FOCAL-12

DECUS NO. 12-70
COMPLT
Harry Bryant, Krusen Research: Center, Temple University,
Philadelphia, Pennsylvania
COMPLT is a SABRised version of the DECUS NO. 8-168
plotting package. It retains all features of that program,
with the additional advantage of allowing it to be called as a
FORTRAN subroutine.
A DECtape version is available for PDP-8 users.
Minimum Hardware:	PDP-12A
Source Language:	PS-8 SABR

DECUS NO. 12-71
Snoopy Display Program
Mark F. Lewis, Civil Aeromedical Institute,
Federal Aviation Administration, Oklahoma City, Oklahoma
This is a paper tape version of the original DECUS NO. L-87.
It is now offered in binary paper tape format for both the
LINC-8 and the PDP-12. (See DECUS NO. L-87a.) The
PDP-12 version has been revised to eliminate the need to
use L8SYM when running on the PDP-12.
The program displays Snoopy and his Sopwith Camel on the
oscillosc0pe.
Storage Requirement:	LIF2: 20-1746; LIF3: 20-647
Source Language:	LAP6-DIAL

DECUS NO. 12-72
Four-Point Smoothing With FPP-12
L. L. Alber, M. W. Overton and Dr. D. E. Smith,
U. S. Food and Drug Administration, Chicago, Illinois
This program was developed to smooth an array of up to 4095
data points stored as 1-12 bit words using the FPP-12. Using
a 4-point least squares quadratic, the data is floated, fitted,
smoothed, fixed and restored in its original location, while
displaying on the CRT.
Minimum Hardware:	8K PDP-12 and FPP-12
Other Programs Needed:	LAP6-DIAL with FPPASM (on tape)
Source Language:	LAP6

DECUS NO. 12-73
8-Point Quadratic Smooth With FPP-12
L. L. Alber, M. W. Overton and Dr. D. E. Smith,
U. S. Food and Drug Administration, Chicago, Illinois
This program has been developed to smooth an array of up to
4095 data points stored as 1-12 bit words using the FPP-12.
Using a 8-point least squares quadratic, the data is floated,
fitted, smoothed, fixed and restored in its original location,
while displaying on the CRT.
Minimum Hardware:	8K PDP-12 and FPP-12
Other Programs Needed:	LAP6-DIAL
Source Language:	LAP6 with FPPASM

DECUS NO. 12-74
*REGRES - Multiple Linear Regression
David C. Howell, University of Vermont, Burlington, Vermont
This is a multiple linear regression pragram which handles up
to 10 predictor variables. The printout includes the means
and standard deviations for each variable, the intercorrelation
matrix, the inverse, and the standard and raw score regression
weights, as well as the multiple correlation coefficients. No
programming knowledge is required of the user once the
system is stored on LINCtape and FOCAL-12 has been loaded.
Although no tapes are offered, anyone using this program will
have no difficulty entering it from the teletype.
Minimum Hardware:	PDP-12 A or B
Source Language:	FOCAL-12 running under the
			DIAL monitor

DECUS NO. 12-75
FORTRAN Subroutines for the PDP-12
Thomas V. McCaffrey, Loyola University Medical Center,
Maywood, Illinois
This package consists of eight subroutines and functions
written for real time control of the PDP-12's clock display,
A to D's sense switches, external line levels, relays and left
switches.
<P>
The ASCII tape offered with the package is a sample FORTRAN
pragram for a time interval histogram which demonstrates the
subroutines.
Minimum Hardware:	8K PDP-12
Other Programs Needed:	8K FORTRAN System or
			PS/8 System
Source Language:	FORTRAN, SABR

DECUS NO. 12-76
TAPELOOK; CORELOOK; SEARCH
David C. Freeman, Harvard Medical School, Boston,
Massachusetts
TAPELOOK, a DIAL tape examiner,requests tape unit 0 or 1,
a tape block (0-777), and displays it as a plot, text, or LINC
code. Tape block may be advanced or backed up from the
teletype, or a new block requested. The index may be
displayed in DIAL format with correct line numbers.
<P>
CORELOOK is usually loaded into an unused instruction field.
It can then examine 8K of core, displaying as octal, text, or
LINC code. A map of any field may be displayed showing all
non-zero locations, and a cursor to display any ten locations.
<P>
Given a search word, SEARCH will examine the DIAL source
working area, and display every line which contains the
search word, with correct line numbers.
Minimum Hardware:	8K PDP-12 with display and
			analog channels
Source Language:	LINC Code

DECUS NO. 12-77
PAL12A Assembler
Mark J. Hyde, Jamesville-DeWitt Central Schools, DeWitt,
New York
PAL12A provides users of smaller PDP-12's with capabilities
formerly available only to those with 8K or more. These
capabilities include 8-mode literals and off-page links,
"LISTAPES," core usage maps and chained assemblies.
Minimum Hardware:	4K PDP-12, 2 LINCtapes, Scope,
			TTY
Other Programs Needed:	4K LAP6-DIAL-V2
Storage Requirement:	All of 4K
Restrictions:		Will run on 4K only. For others
			see write-up
Source Language:	PAL12A

DECUS NO. 12-78
PUBPLOT
William L. Rankin, Veteran's Administration Hospital (116),
San Francisco, California
PUBPLOT was written to produce graphic Plots suitable for
many publication purposes. All input is through the teletype.
When fully utilized PUBPLOT produces a graph with X and Y
axes, numerical and character headings for both axes, seven
lines of any shape, and a scattergwram Any of these segments
of the graph may be deleted according to program specifications.
Minimum Hardware:	4K PDP-12, TTY, COMPLOT
			DP-1-1 or equivalent
Restrictions:		Maximum of 1024(10) input
			characters and values
Source Language:	8-Mode and LINC Assembly
			Languages

DECUS NO. 12-79
Modified ADTAPE
William E. Hatcher, III, Veteran's Administration Center,
Temple, Texas
This patch to ADTAPE will permit ADTAPE to store data on a
LINCtape of 896 (1600(8)) standard blocks. Data files may begin
in any block and may be continuous over blocks 511 and
512 (777(8) and 1OOO(8)). The experiment parameters can be
stored in any of the 896 blocks.
Minimum Hardware:	PDP-12/2O
Other Programs Needed:	ADTAPE (DEC-12-SE2E)
Storage Requirement:	Same as ADTAPE plus locs 7600:-
			7606, 7500-7507, 7700-7706
Source Language:	LAP6

DECUS NO. 12-80
FOCAL-RT
William Siegel and Keith Whittle,
University of Western Ontario, London, Canada
Submitted by. Kenneth Ellson, Digital Equipment Corporation,
Maynard, Massachusetts
Modifications of FOCAL-12 that include device-independent
chaining of FOCAL and assembly-language programs, computed
GOTO and DO commands, new FRAN() function, FIN()
and FOUT() to handle character strings in FOCAL files,
subroutines for opening and closing FOCAL files within
assembly-language programs, LP08 printer option,
return-to-DIAL command, and expanded text buffer.
Minimum Hardware:	8K PDP-12, LINCtapes or Disk
Other Programs Needed:	DIAL-MS Monitor
Source Language:	FOCAL, DIAL

DECUS NO. 12-81
VR12 SCOPE HANDLER FOR OS/8
Mario DeNobili et al
Submitted by: Stanley Rabinowitz, Digital Equipment Corporation,
Maynard, Massachusetts
This is a two-page handler for the PDP-12 VR12 scope.
Display freezes when scope fills up. You go to next scope
page by typing any character. Very useful with PIP.
Minimum Hardware:	PDP-12, PS/8 configuration
Other Programs Needed:	PS/8 system
Storage Requirement:	2 pages
Source Language:	PAL-8

DECUS NO. 12-82
LAP6-DIAL TO PS/8 SOURCE FILE CONVERTER
Mario DeNobili
Submitted by: Stanley Rabinowitz, Digital Equipment Corporation,
Maynard, Massachusetts
This program allows you to convert source files stored on
LAP6-DIAL LINCtapes (400 words per block) to any PS/8 file.
It runs under PS/8.
Minimum Hardware:	PDP-12, PS/8 configuration
Other Programs Needed:	PS/8 system
Source Language:	PAL-8

DECUS NO. 12-83
\$ANOVARM - ONE WAY ANALYSIS OF VARIANCE FOR
REPEATED MEASURES DESIGN
A. 5. Craig, Research Dept., Lakeshore Psychiatric Hospital,
Toronto, Ontario
This program produces the standard ANOVA Table for a
Repeated-Measures Design.
Minimum Hardware:	PDP-12 with 8K core
Other Programs Needed:	FOCAL 12 with extender patch as
			per FOCAL 12 Manual Appendix E
Restrictions:		Number of subjects and treatments
			<= 57; Number of subiects and
			treatments <= 850
Miscellaneous:		Reference: B. J. Winer, Statistical
			Principles in Exp't Design 2nd
			edition, chapter 4, 1971
Source Language:	FOCAL

DECUS NO. 12-84
AVERAGER
Richard W. Reeder, State University of New York,
Stony Brook, New York
Used to simultaneously average 5 channels of analog data
such as EEG, ECG, etc. and store the average on LINCtape.
Minimum Hardware:	8K, EAE, KW12A, TU55 (2) A/D
Storage Requirement:	0-2000, 4000-7777; field 1
			0000-7777
Source Language:	DIAL

DECUS NO. 12-85
APOLLO 12
Andres J. Magre, COASIN S. A., Buenos Aires, Argentina
Simulates the Apollo descending on the moon surface. The
operator governs the fuel rate. The program takes the fuel rate
and makes all calculations every one second, thus operating
in true real time. Indicators and time-altitude diagram are
displayed.
<P>
Two versions arefiupplied, the second of which uses the
sense switch to guard against over-enthusiastic players.
Minimum Hardware:	PDP-12A 8K
Other Programs Needed:	Version I: FOCAL-12 interpreter
			Version 2: FOCAL-12 and
			DECUS NO. 12-24
Miscellaneous:		This is a modification of "Moon
			Landing“ demo. program published
			in DEC-O8-XJFB-D FOCAL
			Demonstration Programs
Source Language:	FOCAL-12

DECUS NO. 12-86
ORGAN-AA and ORGAN+BA
Andres J. Magre, COASIN S. A., Buenos Aires, Argentina
Program to allow use of the PDP-12 to simulate organ music.
Two versions are supplied. One allows the user to play directly
from the keyboard. The second is similar, but the notes are
first stored in core and retrieved consecutively each time any
key is struck.
Minimum Hardware:	PDP-12, 4K core
Storage Requirement:	Approximately one 8-mode page
			Variable from there
Source Language:	PAL III

DECUS NO. 12-87
ONDISK-OFFDISK
R. D. McCook and T. V. McCaffrey,
Department of Physiology, Loyola University,
Maywood, Illinois
The two programs, OFFDISK and ONDISK, provide the
capability of easily dumping the contents of a DF/DS-32 disk
onto LINCtape and restoring the disk with the tape image at a
later time. The disk image files are indexed and filed under
the DIAL monitor and up to five disk images can be stored on
a 1600 block LINCtape.
Minimum Hardware:	8K PDP-12, TU-55 tape transport
			DF-32 disk
Other Programs Needed:	DIAL-V2 (supplied)
Storage Requirement:	8K can be modified for 4K
Restrictions:		Restricted to DF/DS-32 disk
Source Language:	DIAL

DECUS NO. 12-88
OCTALFPP
Arnold Gershon
Submitted by: Professor Se Jeung Oh, City College, New York
An octal translation of a single length floating point package
for use on a PDP-12 computer. Inputs, outputs, does various
floating point operations on floating point numbers.
Minimum Hardware:	PDP-12A
Storage Requirement:	Locations 40-6I , 5600-7577
Source Language:	DIAL-V2

DECUS NO. 12-89
BUTFLTR
Arnold Gershon
Submitted by: Proffesor Se Jeung Oh, City College, New York
An engineer-interactive design program for the PDP-12. Will
display frequency response of low pass Butterworth filter of
order 1 <= n <= 64 and calculate parts valves for same for any
cutoff frequency and any matched input/output impedance.
Minimum Hardware:	PDP-12A
Other Programs Needed:	OCTALFPP (DECUS NO. 12-88)
Storage Requirement:	With OCTALFPP approximately 2600 words
Source Language:	DIAL-V2
July 1974

DECUS NO. 12-90
REPRSNT
Arnold Gershon
Submitted by: Professor Se Jeung Oh, City College, New York
Formulates octal representation of floating point numbers
required as constants. Program inputs a number from teletype
then outputs the correct octal representation of the number.
Minimum Hardware:	PDP-12A
Other Programs Needed:	OCTALFPP - DECUS NO. 12-88
Storage Requirement:	74(8) words plus approximately
			2000 words for OCTALFPP
Source Language:	DIAL-V2

DECUS NO. 12-91
OCTPUNCH
Arnold Gershon
Submitted by: Professor Se Jeung Oh, City College, New York
Program will punch a source paper tape containing the octal
equivalent of a specified section of core. This tape can then
be assembled at a later time faster than its original source
could be and without any conflicting symbols which the
original might have contained.
Minimum Hardware:	PDP-12A
Storage Requirement:	143(8) words
Source Language:	DIAL-V2

DECUS NO. 12-92
PDP8TO12
Arnold Gershon
Submitted by: Professor Se Jeung Oh, City College, New York
Short utility routine for making a source tape produced by a
PDP-8 acceptable to a PDP-12.
Minimum Hardware:	PDP-12A
Storage Requirement:	18 words
Source Language:	DIAL-V2

DECUS NO. 12-93
TRANS
Arnold Gershon
Submitted by: Professor Se Jeung Oh, City College, New York
Will translate a BIN paper tape to an octal Source paper tape.
The octal source can then be assembled together with other
routines. In addition, the translation will satisfy any curiosity
about what a particular BIN tape contains.
Minimum Hardware:	PDP-12A
Storage Requirement:	738 words
Source Language:	DIAL-V2

DECUS NO. 12-94
DATAN
Pietro Morasso
Submitted by: Jean Graham, M.I.T., Cambridge, Massachusetts
DATAN is used to analyze psychophysical and neurophysiological
data, collected on DECtapes. Analysis is done with a
number of computing modules, which execute simple operations
like smoothing, scaling, linearizing, computing calibrations,
measurements and derivatives, etc. Linking
different modules may be manual or automatic.
Minimum Hardware:	PDP-12B (8K) + 2 LINCtape
			units + 1 RS08 or RK8 disk
Other Programs Needed:	FOCAL-12
Storage Requirement:	8K
Source Language:	FOCAL-12

DECUS NO. 12-95
PDP-12 PS/8 Utility Programs
Charles M. Moore, III, 1700 Sunset Blvd., Houston, Texas
This package contains the following utility programs, along
with their sources.
<P>
1) MAGSPY displays the contents of any block on any PS/8
device, using any of several modes selected by the sense
switches. Included is a mode which displays PS/8 source
files as text listings.
<P>
2) INDEX displays PS/8 device indices, deletes files with
rubouts, transfers groups of one or more files from one
device to another.
<P>
3) COPY duplicates entire PS/8 LINCtapes.
<P>
4) MARK12 marks LINCtapes.
<P>
5) DIALPS copies files from DIAL LINCtape 1 to PS/8 device
<P>
SYS, automatically converting core-image file headers.
<P>
6) PSDIAL copies files from PS/8 to DIAL.
MAGSPY, INDEX and COPY use SABR routine IHELP to
display operating instructions.  Other SABR or FORTRAN
programs can also use IHELP.
Minimum Hardware:	8K PDP-12 with scope
Other Programs Needed:	PS/8 System
Source Language:	SABR

DECUS NO. 12-96A,B
SCOPE and CNGMWA
Carol Horwitz, Philip Reid,
Richard LeFaivre (A); Carol Horwitz (B)
Submitted by: Michael E. Clark, Laboratory Computer Facility,
University of Wisconsin Medical Center, Madison, Wisconsin
A. SCOPE is a CRT-based editor for the PS/8 (or OS/8)
system on a PDP-12. A user-selected portion of the source
text is in full view on the CRT during editing. Features include
character editing via a key-controlled cursor, full
forward and backward movement through the source, the ability
to search for specified text strings, and horizontal tabbing.
The Command set for SCOPE is small and easily learned.
SCOPE is loosed upon the LAP6W (and hence LAP6) manuscript
editors.
<P>
B. CNGMWA is a support pragram for SCOPE, the scope oriented
PS/8 editor. CNGMWA may be used to change the size
of SCOPE's internal scratch file, allowing larger source
programs to be edited.
Minimum Hardware:	8K PDP-12, VR14 CRT or similar
			CRT
Other Programs Needed:	PS/8 or OS/8
Source Language:	PAL-8 and LAP6W.

DECUS NO. 12-97
An Off-Line FOCAL-12 Program for Auto-Analyzer by TWX
L. L. Alber and Mack W. Overton,
U. S. Food and Drug Administration, Chicago, Illinois
Data being input by teletype or paper tape reader is displayed
on the CRT. Instrument readings are transmitted long-distance
to the computer by TWX. Program calculates values for each
cup reading, a standard deviation and coefficient of variance
report.
Minimum Hardware:	8K PDP-12
Other Programs Needed:	FOCAL-12
Source Language:	FOCAL-12

DECUS NO. 12-98
HERALD - Analog-Digital Average and Standard Error Program
David Johnson, University of Ulm, West Germany
Averages 8 channels of analog data and calculates +/- 2
standard error limits. Curves of sequential S.E. also are
provided and automatic correction of drift (Zero-Line),
calibration data storage on tape, curve display and plotting
and data typeout. Allows intra-individual statistical comparison
i.e. Evoked Potentials.
Minimum Hardware:	8K PDP-12 with A-D, VR-12
			Display, basic LINCtape system,
			ASR33, KW12, KE12
Restrictions:		+0.5 volts continuous input
Source Language:	LAP6

DECUS NO. 12-99
A Set of Spectral ngrams
Cyril H. Nute,
Naval Medical Neuropsychiatric Research Unit,
San Diego, California
XSPECT is a pair of programs written for the PDP-12 computer.
Program XS, written in DIAL, accepts 2048 digital data
measurements for each of two EEG channels, written on one
reel of LINCtape mounted on Unit 0. This input record may be
created from analog voltages input to the AD12 analog-to-digital
converter, using the two D.E.C. programs, ADTAPE
and ADCON. The output of programs XS is a three-black
record written on the "intermediate output tape", mounted on
Unit 1.
<P>
The second program of the set is \$XS, written in FOCAL-12,
under the DIAL-MS monitor system. It accepts a three-block
intermediate record from the LINCtape mounted on Unit 1, and
uses the ASR33 teletype to create a listing of two auto-power density
spectra, plus the coherence and phase relationships between the
two EEG data channels. Frequencies are written on the left
edge of the paper, with each line of output representing a
.5-Hz frequency interval.
Minimum Hardware:	8K PDP-12, AD12 analog-to-digital
			converter, KW12 Clock,
			2 LINCtape units, ASR33
Other Programs Needed:	DIAL-MS Monitor System, with
			FOCAL-12; QANDA; FFT
			(DECUS NO. 8-143)
Restrictions:		Need two channels of input data
			on LINCtape, sampled at 128 Hz
			for 16 sec; output resolution in
			.5 Hz.  May be changed by contacting
			the author
Source Language:	DIAL

DECUS NO. 12-100
MEMO III - A Text Formatting Program
Mark F. Lewis, Federal Aviation Administration,
Oklahoma City, Oklahoma
MEMO III is a program written for the OS/8 system to produce
paged text with margins from free form text. The intention is
to permit the user to produce readable and neatly formatted
copy of text with in minimal effort.
<P>
MEMO III is a descendant of Gregory Ruth's original program.
This version permits output on any OS/8 campatible output
device, rather than restricting output to the teletype. Files
written for MEMO nd MEMO II are compatible with MEMO III.
Minimum Hardware:	PDP-8/12, ASR33 (or equivalent)
			and either DECtape or disk
Other Programs Needed:	OS/8 Programming System
Miscellaneous:		Same program is available on
			DECtape as DECUS NO. 8-427b
Source Language:	PAL-8

DECUS NO. 12-101
OS/8 SKED
Mark F. Lewis and Patricia Savage,
Civil Aeromedical Institute, Federal Aviation Administration,
Oklahoma City, Oklahoma
OS/8 SKED is a modification to DECUS NO. 8-465 that
permits the user to take advantage of the device-independence
of OS/8 for compiling and running SKED programs.
Minimum Hardware:	12K for compiler, 8K for run-time
			system, OS/8 configuration, 100
			cycle real time clock, interface
Other Programs Needed:	OS/8 (DECUS N0. 8-465)
Source Language:	PAL-8

DECUS NO. 12-102
A Manual for the PDP-12 Operator
Peter Hiscocks, Ryerson Polytechnical Institute, Toronto,
Ontario, Canada
Most manuals are for the computer; this one is for the operator.
Its purpose is to clarify operating procedures for the PDP-12
console, paper tape loaders, DIAL Operating System,
Peripheral Interchange Program (PIP) and the special PDP-12
peripherals. It was written primarily for students.

DECUS NO. 12-103
\$HAPPY
Roger C. Tindle, Columbia, Missouri
This program generates a happy-face display on the VR12
scope.
Minimum Hardware:	PDP-12, VR12 scope
Source Language:	FOCAL-12

DECUS NO. 12-104
CORDATFP
Ray Cooper, Burden Neurological Institute, Stapleton,
Bristol, United Kingdom
CORDAT computes cross-correlation of two blocks of data
stored on Unit 1 with +/-64 (lag and lead) points. Displays
on oscilloscope and plots on incremental plotter.
Minimum Hardware:	8K PDP-12, Plotter (optional)
Other Programs Needed:	FPP 12
Source Language:	DIAL MS/LAP6

DECUS NO. 12-105
DATAFILE and DFUPDATE
C. M. Malpus, Ph.D., University of Leeds,
Department of Physioiogy, Leeds, United Kingdom
DATAFILE is a LINCtape-based display-interactive library
designed primarily as a transparent system by which data from
user programs can easily be stored, edited and retrieved. The
only addition needed to any user pragram to add filing capabilities
is a short loader routine, and only one memory location
is modified when the program is restarted.
<P>
Binary programs can also be stored and DATAFILE can be used
as a free-standing library. system, started from the console and
capable of loading and starting the binary programs filed within
it.
<P>
DATAFILE thus takes over the binary library and loading
facilities of DIAL, and can additionally be called from (and
exit to) user programs to file resultant data. Because of its
compactness and its increased file and index space it is much
more efficient, as well as easier to use, than DIAL for debugged,
operational programs.
<P>
DFUPDATE is the means by which new binary programs are
added to a DATAFILE program library. Programs are transferred
from the DIAL binary working area on a LINCtape to a
DATAFILE file on the same or another LINCtape, and the
index updated accordingly. Once filed by DFUPDATE, such
programs can be loaded and started by DATAFILE.
Minimum Hardware:	VR 12/14, TC12, TU55 or TU56,
			TTY, AD12
Restrictions:		DECtape Handlers only. No disk I/O
Source Language:	DIAL

DECUS NO. 12-106
\$PLOT
Frank Sandy, Raytheon Research Division, Waltham,
Massachusetts
This is a FOCAL-12 overlay that allows an incremental
digital plotter to be operated from a FOCAL program on a
PDP-12. It can be used to draw lines or points with FOCAL's
extra function FX, or to draw characters with FOCAL's extra
function FZ.
<P>
Editor's Note: There is another \$PLOT routine included in
OVERLAYS T0 FOCAL-12 (DECUS NO. 12-24)
Minimum Hardware:	8K PDP-12, LINCtape or disk,
			Digital Incremental Plotter
Other Programs Needed:	FOCAL-12 and \$CHAR (included
			on tape for \$PLOT)
Storage Requirement:	Overlay locations 4247-4612
Restrictions:		Limited by plotter for lines,
			slightly slower for characters
Source Language:	LAP6

DECUS NO. 12-107
AVUPTOB, AVUPTOBS
A. M. Halliday, Medical Research Council, National Hospital,
London, United Kingdom
A flexible multichannel averaging program for evoked responses,
allowing choice of number of sweeps, channels and
sampling rate via the teletype. Averaged data can be stored
or retrieved from tape (1600 blocks with AVUPTOBS) and
plotted out. Display monitors running sum or current input.
The averaging sweep is triggered by an external pulse on the
chosen sync input.
Minimum Hardware:	8K PDP-12A, KW12, Houston
			Complot DPT, XY plotter
Other Programs Needed:	LAP6-DTAL
Restrictions:		Up to 8 channels. Maximum sampling
			rate: 10 Kcs/number of channels
			chosen
Source Language:	LAP6-DIAL

DECUS NO. 12-108
FPPNEW - Replacing the DIAL-MS-Assembler by an improved
Version of the FPP Assembler
Juergen Stegemann, M. D., Deutsche Sporthochschule Cologne,
Cologne, West Germany
For a PDP-12 user it is a serious disadvantage that the FPP
Assembler (DEC-12-AQZA-D) is not able to produce LINC
codes and that it does not work with one DF32 in connection
with LINCtapes. Therefore an improved program is offered
to get nearly full compatibility to the DIAL-MS assembler as
well as to the FPP system. Since the DTAL-MS assembler has
no advantage any more, it was replaced by the new program.
Some additional features are added, which are not included
in both assembly programs now.
Minimum Hardware:	8K PDP-12A, 1 MC12, 1 FPP12,
			1 DF32
Other Programs Needed:	DIAL-MS
Source Language:	Assembler

DECUS NO. 12-109A,B,C
QNANSWER, QANDATTY, SUPRSHUF
Ronald W. Wood, University of Rochester School of Medicine,
Rochester, New York
A. QNANSWER retrieves information from the QANDA
(DEC-12-FISA-D) answer buffer, ignoring terminal null
values. The program accepts 8's and 9's as octal 10's and
11's. Each question field within a display is limited to a
maximum of four characters. The program occupies. 38(10)
locations, B16 and B17.
<P>
B. QANDATTY prints QANDA (DEC--12-FISA-D) displays
and user responses on the teletype. The program occupies
102(10) memory locations and utilizes Beta registers 2 through
6. It provides the user the option of printing several display
lines to the teletype line.
<P>
C. SUPRSHUF shuffles data with a pseudo-random algorithm
which repeats every 512 non-zero input data points.
<P>
Tape contains source files for QNANSWER and QANDATTY;
cor binary and source files for SUPRSHUF.
Minimum Hardware:	4K PDP-12, TTY, scope, 2 tape
			units
Other Programs Needed:	QANDA (DEC-12-FISA-D)
Source Language:	DIAL-MS

DECUS NO. 12-110
DIAL-MS for 1600 Blocks
David Goodman, Psychophysiology Laboratory, V.A. Hospital,
Bedford, Massachusetts
DIAL-MS, version SE2E, cannot directly access LINCtape
blocks greater than 777 in any of its operations. DIAL-MS
for 1600 Blocks, by means of patches to most of the routines
and reassemblies of the ADD PROGRAM routine and PIP,
has been modified to access all 1600 blocks in all of its
routines.
Minimum Hardware:	8K PDP-12, 2 LINCtapes marked
			with 1600 (octal) standard blocks
Restrictions:		Has not been tested on a disk
			system
Source Language:	DIAL-MS

DECUS NO. 12-111A
Harry Bryant, Moss Rehabilitation Hospital,
Krusen Research Center, Philadelphia, Pennsylvania
ADFILE, a modification of ADTAPE to run under PS/8 on a
PDP-12A, is a data acquisition program that permits from one
to sixteen AD12 A/D channels to be sampled consecutively.
Minimum Hardware:	8K PDP-12A with KW12A, AD12,
			(RF08 disk optional)
Other Programs Needed:	PS/8 Operating System
Restrictions:		Must be run on a PDP-12A with
			LINCtapes or RF08 disk as output
			device; PS/8 or OS/8 must be built
			with CONFIG -- not BUILD
Source Language:	PAL-8

DECUS NO. 12-112
IDXRDD
Harry Bryant, Moss Rehabilitation Hospital,
Krusen Research Center, Philadelphia, Pennsylvania
TDXRDD is a collection. of FORTRAN callable subroutines for
reading PS/8 unformatted data files, such as the output for
ADFTLE (DECUS NO. 8-211a). The subroutines contained in
the package are: INDEX, RDHAN and NAMUD.
<P>
INDEX will perform a directory search on a device file
specified at the keyboard by the user in a standard PS/8
command line.
<P>
RDHAN allows reference for reading last device handler
specified in a call to INDEX.
<P>
NAMUD allows file name specified in INDEX to be incremented
by octal one forming a new file name. Then the device
directory is searched for the new file name.
Minimum Hardware:	PDP-12A, TTY, Tapes, Disk
Other Programs Needed:	PS/8 monitor
Restrictions:		All subroutines must occupy same
			LINC segment
Source Language:	SABR

DECUS NO. 12-113
IDXWT
Harry Bryant, Moss Rehabilitation Hospital,
Krusen Research Center, Philadelphia, Rennsylvania
IDXWT is a group of FORTRAN callable subroutines needed
for writing unformatted data files on a PS/8 device. The
subroutines are FOPEN, FCLOSE, WITHAN and NAMUP.
<P>
FOPEN performs a file search and opens a tentative file on a
PS/8 device. WITHAN allows the user to write unformatted
files on the PS/8 device loaded when FOPEN was called.
<P>
FCLOSE closes the tentative file opened in FOPEN.
<P>
NAMUP allows the file names specified in FOPEN to be
incremented by octal one forming a new file name. A
tentative file is then opened using the new file name.
Minimum Hardware:	PDP-12A, TTY, LINC, Tape, Disk
Other Programs Needed:	PS/8 monitor
Source Language:	SABR

DECUS NO. 12-114
FOCAL-PL
T. V. McCaffery and R. D. McCook, Dept. of Physiology,
Loyola University, Maywood, Illinois
This is a modification of FOCAL-12 which allows data plotted
on the screen to be transferred to a digital plotter. This program
works with a Houston DP-1 plotter, but others could probably
be used. It does not occupy any user space but uses the scope
text buffer, thereby making the scope text feature inoperative.
Minimum Hardware:	8K PDP-12, Digital plotter, EAE
			optional
Restrictions:		Destroys text storage on scope
Source Language:	DIAL

DECUS NO. 12-115
PLOT3D, Pseudo 3-Dimensional Perspective Display for the
PDP-12
Michael F. Lubozynski and John A. Freeman,
Vanderbilt University School of Medicine, Nashville, Tennessee
PLOT3D is a LINC-mode pragram which will produce a
pseudo 3-dimensional display of up to 16 256-word waveforms,
shown at any desired perspective (and scale) and interconnected
by a user-specified number of contour lines.
Minimum Hardware:	8K PDP-12
Restrictions:		All input must be in octal
Source Language:	DIAL-MS

DECUS NO. 12-116
FPP-12/FOCAL-12 Reduction of Auto Analyzer Data for
Pharmaceuticals
L. L. Alber, M. W. Overton and Dr. D. E. Smith,
U. 5. Food and Drug Administration, Chicago, Illinois
An 8-point least-squares fitting algorithm for the FPP-12 is
used as a subroutine of FOCAL-12 to reduce Auto Analyzer
data previously stored on LINCtape by ADTAPE/ADCON
operating on-line with up to 16 instruments.
Minimum Hardware:	8K PDP-12, 2 LINCtape units,
			DF32 disk, FPP-12
Other Programs Needed:	FPPASM Assembler
Source Language:	LAP6-DIAL and FPPASM

DECUS NO. 12-117
TAPEDIT; A PDP-12 LINCTAPE EDITOR
Mark J. Hyde, Jamesville-DeWitt Central Schools,
DeWitt, New York
TAPEDIT provides a quick and efficient means of inspection
and modification of data contained on LINCtape. It is an
improvement over previous 4K tape editors in that its principal
output device is the VC12 scope. Output may also be directed
to the console teletype. Data may be interpreted as octal
values, DIAL sixbit characters, or PDP-10 sixbit characters.
Word search and data move functions are also provided.
TAPEDIT will operate properly with tapes up to 4096 blocks
long and with blocks containing up to 512 data words.
Minimum Hardware:	PDP-12A or 12/20 (Scope,
			LINCtape and A/D channels)
Source Language:	LAP6-DIAL V2

DECUS NO. 12-118
Average Transient Advanced Programs
C. M. Malpus, Ph.D., Department of Physiology,
University of Leeds, Leeds, United Kingdom
These programs each offer advances over previous DEC or
DECUS average transients construction programs. Both are
easy to use with flexible very fast (30 usec point minimum)
data collection routines. AVTRCOMP allows non-simultaneous
collection of up to four transients, with commands for subsequent
arithmetic combination, cross-comparison, differentiation
and integration. AVDEVVAR collects one transient only, but
calculates the variance of each point; thus confidence limits
or a. variation envelope can be placed on an average transient,
allowing significance of difference assessments to be made.
<P>
These programs may be located and run from standard DIAL
file, but are optimally used in conjunction with the DATAFILE
library facility, in order to store collected data on
LINCtape.
<P>
The LINCtape supplied contains binaries and sources of both
programs, filed under DIAL; in addition a DATAFILE library
system containing the two binaries occupies the low end of
the tape. This area is reserved in the DIAL index.
Minimum Hardware:	PDP-12, KW12, VR12, AD12, TTY
Storage Requirement:	4K for AVTRCOMP, 8K for AVDEVVAR
Source Language:	DIAL

DECUS NO. 12-119
Neuron Spike Train Analysis Programs
C. M. Malpus, Ph. D., Department of Physiology,
University of Leeds, Leeds, United Kingdom
Three of the basic presentation methods for single neuron spike
train data are carried out by these programs. A flexible data
collection routine allows simultaneous collection of two independent
spike trains. FREQHIST constructs instantaneous
frequency histograms, PSTMHIST Constructs post-stimulus
histograms and INTVHIST interval histograms. All displays
are fully calibrated and can be scaled and expanded by the
operator. FREQHIST and PSTMHIST can simultaneously
collect one channel of analog information for later monitoring
or cross-correlation.
<P>
These programs may be loaded and run from standard DIAL
files, but are optimally used in conjunction with the
DATAFILE library facility, in order to stare collected
data on LINCtape.
<P>
The LINCtape supplied contains binaries and sources of all
three programs filed under DIAL. In addition a DATAFILE
library system containing the three binaries occupies the low
end of the tape. This area is reserved in the DIAL index.
Minimum Hardware:	4K PDP-12, KW12, VR12, AD12,
			TTY
Source Language: DIAL

DECUS NO. 12-120
DUAL Assembler
John R. Raines, Northwestern University Medical School,
Chicago, Illinois
DUAL is derived from QUIP, DECUS NO. 12-54. It has
been given extra pseudo-ops, etc. to make it nearly DIAL
compatible. In addition, it offers literals; address
multiplication, division and rotation; several fold increase
in assembly speed; a second set of conditional assembly
pseudoops and some additional pseudo-ops. Updated August 1973.
Minimum Hardware:	PDP-12 with DIAL-MS and EAE,
			TTY, preferably ASR35
Source Language:	DUAL

DECUS NO. 12-121
Arrhythmia Detection and Categorization
Roy James Stanfill, Bioengineering Division,
University of Washington, Seattle, Washington
This is a real-time QRS detection and analysis routine based
upon R-wave slope detection. The ECG, filtered from 3 Hz
to 40 Hz, is input to the A/D Converter. Each QRS is compared
with a stored average and judged normal or abnormal;
the R-R interval is also checked to determine whether the beat
is early or late.  Several displays are available. Every 10
minutes, or upon request, the number of beats and arrhthmias
for the preceding 10 minutes, are typed out. If a Tektronix
video terminal and hardcopy Unit are available, copies of the
displays can be made via the sense switches and relays.
Minimum Hardware:	5K; PDP-12; EAE
Source Language:	DIAL-MS

DECUS NO. 12-122
PDP-12 User's Monitor Command
Mark J. Hyde, Jamesville-DeWitt Central Schools, DeWitt,
New York
This is an implementation of the DIAL user's monitor command
functions as an extension of the 4K LAP6-DIAL-V2 system.
It provides the user of such a System with a convenient way to
zero the working area of any tape unit, merge binary files,
and respecify the assembler permanent symtol tables.
Minimum Hardware:	Same as 4K DIAL
Other Programs Needed:	LAP6-DIAL
Source Language:	LAP6-DIAL

DECUS NO. 12-123A
OS/8 VR12 Handler
Edward Rapoport, Institute of Child Development,
University of Minnesota, Minneapolis, Minnesota
Revised by: Roger Abel, Colorado State University,
Fort Collins, Colorado
The VR12 handler is an OS/8 - PS/8 output handler which
utilizes the standard VR12 cathode ray tube display of the
PDP-12 as a standard OS/8 device-independent output
device. This two page handler displays ASCII text frame by
frame with the user controlling the advancing of frames from
the console keyboard.
Minimum Hardware:	8K PDP-12 with VR12 scope
Other Programs Needed:	OS/8 BUILD or CONFIG source
Restrictions:		Output buffer must begin on even
			address. Binary is in OS/8 BUild
			device handler format
Source Language:	PAL-8

DECUS NO. 12-124
FR, FDIS and FADC for PDP-12 Input/Output
Lawrence Moss, Cardiopulmonary Lab.,
University of Vermont, Burlington, Vermont
Three special patches to PS/8 FOCAL are implemented for
use with the special LINC mode input-output devices of the
PDP 12. These are FADC for the analog-to-digital converters,
FDIS for the KW12(KW14) display, and FR which will sample
the sense switches and turn any relay on or off.
Minimum Hardware:	8K PD P-12 with mass storage
			device
Other Programs Needed:	PS/8-12, OS/8-12, OMSI PS/8
			FOCAL (DECUS FOCAL8-177)
Source Language:	PAL-8

DECUS NO. 12-125
Waveform Analysis
Roy James Stanfill, University of Washington, Seattle,
Washington
This is a real-time waveform analysis routine. The waveform
is sampled and continuously displayed. The waveform can be
frozen, via the sense switches, and the minimum and maximum
values of the waveform determined (and indicated). Two
cursors, controlled by the A/D Converter pots, are displayed
congruous to the waveform; their horizontal and, vertical
absolute differences are displayed. The routine is particularly
useful for analysis of physiological signals, i.e., calculation
of QRS width, S-T interval, R-R interval, etc.
Minimum Hardware:	PDP-12 with TTY, API and EAE,
			KW12
Source Language:	DIAL-MS

DECUS NO. 12-126
WAVEFORM: Evoked Potential Analysis
T. Joe Willey, School of Mediciine, Loma Linda University,
Loma Linda, California
This program reads single or double-precision data from LINCtape;
displays a waveform, baseline and cursor; and finds peaks
and zero-crossover points for principal evoked potential
deflections.  The complex waveform is reduced to fundamental
waveform descriptors in terms of amplitude, latency, rise,
fall and peak area. The program also estimates coefficients
to an elemental waveform involving a damped sinusoidal
function that characterizes the evoked potential. The program
has general application in neurophysiology but may be useful
to other kinds of problems involving data reduction and
analysis.
Minimum Hardware:	8K PDP-12, EAE, VR12,
			2 LINCtapes, TTY, A/D Converter
Source Language:	LAP6-DIAL-MS

DECUS NO. 12-127
Withdrawn
Unkown

DECUS NO. 12-128
GEP: A Generalized Experimental Package
Gregg C. Oden and Stanley Wong, Department of Psychology,
University of California at San Diego, La Jolla, California
The Generalized Experimental Package is designed to allow
the naive user of a PDP-12 to utilize its full capabilities in
running a broad range of judgmental experiments in psychology,
sociology, economics, etc.
<P>
The dual channel facilities of the VR-12's or VR-14's are
used to allow installations with two external scopes to run two
subiects completely independently; each subiect may proceed
at his own rate and each receives a different randomized presentation
sequence. The stimuli may be any set of verbal
materials, including personality trait adjectives, short
sentences, product names, etc. Responses are made through use
of a continuous graphic rating scale which is drawn on the
scopes.
<P>
The user specifies the characteristics of his experiment with a
simple conversational initialization program. This program
requires no knowledge of system details and need only be run
once for each new experiment.
Minimum Hardware:	PDP-12, 4K, TTY (2 external
			VR-12's or VR-14's to run 2
			subjects)
Other Programs Needed:	Pseudo Random Number Generator
			(DECUS NO. L-64)
Source Language:	LAP6

DECUS NO. 12-129
OS/12S Scope Monitor Operating System
D. Lloyd Rice, University of California at Los Angeles,
Los Angeles, California
This modification of OS/12 provides scope display of the user
interaction for both monitor and command decoder lines.
Teletype echo may be turned on or off by control characters.
The scope routines are swapped out so they are invisible to all
programs, making the system functionally identical to OS/12.
Minimum Hardware:	8K PDP-12 with mass storage
			device
Source Language:	PAL-8

DECUS NO. 12-130
COMPARE - Fast LINCtape Compare
James C. Good. Jamesville-DeWitt Central Schools,
Syracuse, New York
COMPARE is an efficient means for 4K PDP-12 users to
compare blocks on LINCtape. It recognizes extended units
and utilizes extended addressing. The program compares 7
blocks at a time, although to minimize tape motion it alternates
the reading of "from" and "to" blocks. I. E. it will
alternate reading "from" & "to" blocks with reading "to" &
"from" blacks. So in effect the program compares 14 blocks
at a time. It also allows the user to limit the comparison to a
specified section of each block.
Minimum Hardware:	4K PDP-12, TTY, 102, One
			LINCtape drive
Other Programs Needed:	PAL 12-A (DECUS NO. 12-77)
Restrictions:		Must be assembled with PAL 12-A
			Assembler, maximum block length
			on tape is 400 words (octal)
Source Language:	PAL 12-A

DECUS NO. 12-131
OS/8 DIBILD - Revised
John C. Alderman
Revised by: Mark F. Lewis, Civil Aeromedical Institute,
Federal Aviation Administration, Oklahoma City, Oklahoma
OS/8 DIBILD is a PS/8 or OS/8 utility program to restore
directories that have been overwritten. This version is a
revision of John Alderman's original program (DECUS NO.
8-599), revised to correct coding that was illegal on straight
(or 'classic') PDP-8's. One option has been added.
Minimum Hardware:	Any PS/8 or OS/8 installation
			with LINCtape
Source Language:	PAL-8

DECUS NO. 12-132
LISP 1.5 Interpreter for PDP-8 with OS/8 (PS/8), OS/12
Larry Davis, Washington University, and Torbiorn Alm,
Autocode AB
Submitted by: Robert Hassinger, Liberty Mutual Research
Center, Hopkinton, Massachusetts
Modified version of 8-102a for use under OS/8 (PS/8), OS/12.
OS/8, OS/12 file input and output is allowed, which allows
the user to prepare LISP programs using OS/8, OS/12 EDIT.
Input and output in ASCII. Facilities for writing own code in
assembler to be added to the interpreter for evaluation of
special functions are provided for.
Minimum Hardware:	PS/8, OS/8 or OS/12
Other Programs Needed:	PS/8, OS/8, OS/12 Operating
			System
Storage Requirements:	8K
Source Language:	PAL-8

DECUS NO. 12-133
MINT - Multiple Precision Integer Arithmetic Subroutine
Larry Davis, Washington University, St. Louis, Missouri
Submitted by: Robert Hassinger,
Liberty Mutual Research Center, Hopkinton, Massachusetts
Arithmetic and input-output subroutines are provided for
multiple precision integers.
Minimum Hardware:	PS/8, OS/8, OS/12
Other Programs Needed:	PS/8 FORTRAN or PS/8 SABR
Source Language:	SABR

DECUS NO. 12-134
RWDF32
Larry Davis, Washington University, St. Louis, Missouri
Submitted by: Robert Hassinger,
Liberty Mutual Research Center, Hopkinton, Massachusetts
This FORTRAN and SABR callable program allows blocked
input and output from DF32 disks where the block size is a
parameter.
Minimum Hardware:	PS/8, OS/8, OS/12, DF32 disk
Other Programs Needed:	PS/8 FORTRAN or PS/8 SABR
Source Language:	SABR

DECUS NO. 12-135
MAC8, 8K MACRO ASSEMBLER
Larry Davis, Washington University, St. Louis, Missouri
Submitted by: Robert Hassinger,
Liberty Mutual Research Center, Hopkinton, Massachusetts
MAC8 is an 8K assembler which runs under PS/8, OS/8 or
OS/12. It allows macros to be written along with other
assembly language instructions.
Minimum Hardware:	PS/8 OS/8, OS/12
Storage Requirement:	8K
Source Language:	PAL-8

DECUS NO. 12-136
MOVE
Larry Davis, Carl Ralston, Washington University, St. Louis,
Missouri
Submitted by: Robert Hassinger,
Liberty Mutual Research Center, Hopkinton, Massachusetts
MOVE is an OS/8 program for transferring files from one,
directory device to another directory device. It is efficient
since it reads the input and output device directories only
once.
Minimum Hardware:	OS/8, OS/12 configuration
Other Programs Needed:	OS/8 or OS/12, Version 1 (May
			work with OS/8, V2)
Storage Requirement:	8K
Miscellaneous:		Changes given in document to
			make MOVE work with PS/8
Source Language:	PAL-8

DECUS NO. 12-137
PAL12D
Larry Davis, Washington University, St. Louis, Missouri
Submitted by: Robert Hassinger,
Liberty Mutual Research Center, Hopkinton, Massachusetts
PAL12D (Davis) is a modification of the PAL-8 Assembler to
allow either PDP-8 or LINC mnemonics.
Minimum Hardware:	PS/8, OS/8, OS/12 Configuration
Storage Requirement:	8K
Source Language:	PAL-8

DECUS NO. 12-138
ISEL
Larry Davis, Washington University, St. Louis, Missouri
Submitted by: Robert Hassinger,
Liberty Mutual Research Center, Hopkinton , Massachusetts
It is often desirable to check if a certain LINCtape unit is
selected or write-enabled before doing some operation on it,
in order that a message may be printed if not.
<P>
ISEL is a FORTRAN or SABR callable function which returns
-1 if the unit specified is not selected, returns 0 if the unit
specified is selected and not write-enabled, and returns 1 if
the unit specified is selected and write-enabled.
Minimum Hardware:	PS/8, OS/12, PDP-12 LINCtape
Other Programs Needed:	PS/8 FORTRAN or PS/8 SABR
Source Language:	SABR

DECUS NO. 12-139
BURST Analysis Package
John T. Williams and Thomas L. Babb,
U.C.L.A. Center for Health Sciences, Los Angeles, California
This package contains three programs for editing point process
data from STAP-12 trains into definable bursts (minimum of
two intervals) (BRSTEDIT), which can then be printed
sequentially (BRSTPRNT) and stored as a continuous train
for statistical analysis (BRSTRAIN).
Minimum Hardware:	4K PDP-12
Other Programs Needed:	STAP-12 (DECUS NO. 12-34)
Restrictions:		Acceptable input limited to
			stap-12 trains
Source Language:	DIAL-MS

DECUS NO. 12-140
NAEP - Nerve Action and Evoked Potentials
T. J. Willey, N. Fleming and F. Roos, Loma Linda University,
School of Medicine, Loma Linda, California
The programs in the NAEP series were developed for investigations
of neuro-electric events in the nervous system. Some
are specific to a particular environment or experimental
outlook but most have general applicability to data processing
in the neurosciences. All are called through an executive
and are rapidly and easily available for transitions from one to
the next. The system is interactive and adaptive to a. wide
variety of uses.
Minimum Hardware:	8K, A/D converters, VR12, 2
			LINC transports, EAE, TTY, CalComp
			Plotter, X-Y plotter
Restrictions:		Source stored in extended tape
			format
Source Language:	LAP6-DIAL-MS

DECUS NO. 12-141
\$CORREL - Intercorrelation Program for 50 Variables
David A. Paskewitz, Ph.D. and Robert L. Hufgard,
Unit for Experimental Psychiatry,
Institute of the Pennsylvania Hospital,
Philadelphia, Pennsylvania
Reports. Mean, Standard Deviation, Sum of Scores, Sum of
Squares and Correlation Coefficients for up to 50 by 50
Variable matrix. Designed to be both versatile and usable by
inexperienced personnel. Once the initial scope-presented
dialog is completed and data entered at the teletype, the
program will run without further intervention by the user.
Options for sub-group analysis with computation of Mean and
Standard Deviation, with or without the correlation matrix,
are provided.
Minimum Hardware:	8K, Scope, Mass Storage, ASR33
Other Programs Needed:	FOCAL-12 running under DIAL-MS
Source Language:	FOCAL-12

DECUS NO. 12-142
FOCALSD
Mack W. Overton, Jr. and Larry L. Alber,
U. S. Food and Drug Administration, Chicago, Illinois
Utilizes the user function as entrance to the FOCAL-12 file
storage area.
Minimum Hardware:	DF32 disk
Storage Requirement:	FOCAL-12 (DEC-12-AJAA-D)
Source Language:	DIAL-MS

DECUS NO. 12-143
DSLIS - Dead Start Loader and Index Statistics
Edward Rapoport, University of Minnesota, Minneapolis,
Minnesota
Dead Start Loader and Index Statistics is a 3-part utility
routine for DIAL residing in DIAL's free blocks. DSLIS allows
easy loading of any DIAL program without having to go
through the intricacies of the DIAL editor. It is called from
a dead start via a simple switch register command (similar to
and simpler than DIAL). Then any DIAL program name may
be typed in via a QANDA frame and the program is loaded
and started.
<P>
Another part of DSLIS is called by the DIAL "MC" monitor
command. It displays the number of free blocks on a tape or
disk and the location and size of the biggest free space.
Another "MC" command also unloads all active LINCtapes.
Minimum Hardware:	4K PDP-12 with LINCtape
Source Language:	LAP6-DIAL

DECUS NO. 12-144
ANECDOTE- Advanced NeuroElectric Computer Data
Operational Tape (Export)
R. Cooper, W. J. Warren, P. V. Pocock,
Burden Neurological Institute, Bristol, England
ANECDOTE is a package of 12 programs useful in the analysis
of electroencephalographic and other similar time-series
data. Included are programs for general data manipulation
such as scaling, integrating, rectifying, filtering and also
for plotting, averaging, correlation, frequency analysis (FFT)
and pattern recognition. Data is assumed stored on LINCtape
(1600 blocks), 1 sample/block, I point/word. Updated
versions of DECUS library programs 12-63 are included, as
are a few tape handling programs.
<P>
The FPP 12 floating point processor is used in two of the
programs and a number of them utilize an incremental plotter.
Minimum Hardware:	8K, PDP-12, Incremental Plotter,
			FPP12, TTY
Miscellaneous:		DECUS library programs DECUS
			NO. 12-63 are included in
			updated versions
Source Language:	DIAL-MS

DECUS NO. 12-145A
CREFNMAP
John R. Raines, Northwestern University Medical School,
Chicago, Illinois
This is an 8K cross referencer which handles up to 753
symbols and 4095-2*NSYM references. Its main advantage
is in its ability to cross reference some programs which are
too big for CREF12 (which has a maximum capacity of
NSYM*5+NREF=4094). CREFNMAP will work with listapes
produced by either DIAL or DUAL (DECUS NO. 12-120a).
With DUAL listapes, it can produce a core usage map as well.
Minimum Hardware:	8K, EAE, TTY (preferably ASR35)
Other Programs Needed:	DIAL-MS
Source Language:	DUAL (DECUS NO. 12-120a)

DECUS NO. 12-146
\$CORR. (FOCAL Version)
Jim Hoare, Lakeshore Psychiatric Hospital, Toronto, Ontario,
Canada
This program computes the means and standard deviations and
the matrix of correlation coefficients for multivariate data.
<P>
For the long version it will take a little time for the results.
(Example: 40 minutes for 30 variables by 15 subjects.)
Minimum Hardware:	PDP-12 with TTY
Source Language:	FOCAL-12

DECUS NO. 12-147
*BLIPFUN - Computation of Bandlimited Periodic Functions
and their Hilbert Transforms from Samples
Hermann Kremer, Technische Hochschule Darmstadt,
Darmstadt, Germany
This program computes real-valued bandlimited periodic
functions and the Hilbert transform of such functions, if a
set of equidistant samples is given. The program can be used
in electrical engineering and for the approximation and
interpolation of functions.
Minimum Hardware:	8K, Magnetic Tape Unit, Display
			Scope
Source Language:	FOCAL-12 running under DIAL
			Monitor

DECUS NO. 12-148
STATIS12, A Statistical Package for the PDP-12
P. C. Diegenbach, University of Amsterdam, Amsterdam,
Holland
Statistical package with scope displays to chain to 40
chainable FOCAL-12 programs. Included are normal basic
statistics for non-grouped and grouped data, t-test, skewness
and kurtosis, variance analysis, Sheffe-contrast, regression,
correlation, eigen-values, principal axis (with display),
comparison with normal, binomial, negative binomial,
poisson, hypergeometric and logarithmic distributions and
nonparametric statistics.
<P>
The user reacts by answering on the TTY the questions on the
scope. Knowledge of computer functioning is unnecessary.
Minimum Hardware:	8K, Display, 1 (preferably 2)
			tape unit(s)
Other Programs Needed:	FOCAL- 12, DIAL Monitor
Source Language:	FOCAL- 12

DECUS NO. 12-149
XPIP8: PDP-12 DECtape PIP
Douglas E. Wrege, Georgia Institute of Technology,
Atlanta, Georgia
XPIP8 is a special version of PS/8 PIP for PDP-12 owners with
the TC12-F option. XPIP8 allows direct reading and writing
of PS/8-OS/8 DECtapes mounted on any LINCtape drive on
a PDP-12. It will only work on those machines equipped
with the TC12F option.
Minimum Hardware:	8K, TC12-F option
Other Programs Needed:	PS/8, OS/8 or DECsystem-8
			(DECUS NO. 8-646)
Source Language:	PAL

DECUS NO. 12-150
XPIP10: PDP-10 DECtape to LINCtape Converter
Douglas E. Wrege, Georgia Institute of Technology,
Atlanta, Georgia
PIP10 is a PIP for PS/8 that handles PDP-10 DECtapes This
version reads PDP-10 DECtapes directly via the TC12F
hardware option on PDP-12 LINCtape drives.
Minimum Hardware:	8K PDP-12, TC12-F option
Other Programs Needed:	PS/8, OS/8 or DECsystem 8
			(DECUS NO. 8-646)
Source Language:	PAL

DECUS NO. 12-151
"PSYCHO", A PDP-12 Programming System for Control of
Titration Schedules, Behavioral Data Acquisition and
Summary in Animal Psychophysics
Thomas H. Harding and J. Terry Yates, Purdue University,
West Lafayette, Indiana
The "PSYCHO" system is an elaborate set of programs which
control all facets of an animal psychophysical experiment.
The system consists of three separate programs which are
simultaneously core resident. The programs control the
stimulus presentation and experimental contingencies, collect
“on-line" data, analyze the data statistically and summarize
the data by means of a teletype "print-out", hard-copy
graphs and paper-tape output. The psychophysical method
employed is that of Blough. The general method has
application to numerous animal psychophysical tasks in
which "titration" schedules are used. Instructions for
program modification are included in the program text.
Minimum Hardware:	8K and KW12-A clock, ASR33
			Incremental Plotter
Other Programs Needed:	Floating Point Program
			(DEC12-YQIB-PB)
Source Language:	DIAL-MS

DECUS NO. 12-152
LOAD31K, A Loader for DIAL-MS and 32K of Core
John R. Raines, Northwestern University Medical School,
Chicago, Illinois
The DIAL system offers only an 8K binary work area and hence
no facilities for loading programs into memory fields above
Field 1. This program loads up to 4 binaries and all but the
last 1400(8) words of core.
Minimum Hardware:	DIAL-MS Configuration, 32K of
			Core, EAE
Other Programs Needed:	DIAL-MS; DUAL32; CREF32
			(These. files are all included on
			tape)
Source Language:	DUAL (DECUS NO. 12-120a)

DECUS NO. 12-153A
DUAL32, DUAL-28K Assembler
John R. Raines, Northwestern University Medical Center,
Chicago, Illinois
DUAL32 derives from DUAL. In addition to the features of
DUAL, it has: nestable conditional assemblies, nestable
literals, special character for PAL8 compatibility, larger
l/O buffers for reduced LINCtape motion, larger symbol
table (roughly 2000 symbols), improved listing control for
chained assemblies, and provision for producing
multi-LISTAPE listings.
Minimum Hardware:	DIAL-MS Configuration, ASR35
			preferable, EAE
Source Language:	DUAL (DECUS NO. 12-120a)

DECUS NO. 12-154A
CREF32
John R. Raines, Northwestern University Medical Center,
Chicago, Illinois
CREF32 is a 24K version of CREFNMAP. It is much faster,
allows more symbols, more references, produces a 32K rather
than 8K core map and will process listings which overflow
onto a second tape (produced by DUAL32).
Minimum Hardware:	DIAL-MS Configuration, 24K,
			EAE, ASR35 preferable
Restrictions:		Poor format with undefined
			symbols on DUAL LISTAPES
Source Language:	DUAL (DECUS NO. 12-120a)

DECUS NO. 12-155
MARK12X0
John R. Raines, Northwestern University Medical School,
Chicago, Illinois
This is a version of MARK12 which includes the 128 word
block format. In addition it can determine the tape block
size on the tape mounted on unit 0 and can copy tape 0 onto
tape 1 after formatting tape 1. The program will bootstrap
either DIAL-MS or OS/12 on completion.
Minimum Hardware:	8K PDP- 12, DIAL-MS, LINCtape
Source Language:	DUAL 32 (DECUS NO. 12-153)

DECUS NO. 12-156
MUSIC12
Philip H. Jensen
Submitted by: James C. Good,
Jamesville-DeWitt Central Schools, DeWitt, New York
MUSIC12 is a program for the PDP-12 user which allows use
of the teletype keyboard as a piano keyboard. There are 4
Octaves of notes, including sharps and flats. The music can
be played directly from the keyboard, or from previously
punched paper tape via the teletype paper tape reader.
Other Programs Needed:	Monitor Command
Source Language:	LAP6-DIAL

DECUS NO. 12-157
PLOTVS, Device Independent Graphics
Dennis McGhie, Stanford Medical Center, Stanford,
California
PLOTVS was written to allow plotting on three dissimilar
graphics devices from a single set of software. Plotting
programs are written to drive an incremental plotter, except
the plotter commands are buffered to an OS/8 file. PLOTVS
reads this file and plots the picture on an incremental plotter,
a storage scope, or a line oriented plotter.
Minimum Hardware:	PDP-12 (or 8/I, 8/L or 8/E), EAE,
			Incremental Plotter, Storage
			Scope, Versatec MATRIX 200A
			Printer/Plotter
Other Programs Needed:	OS/8, User written plotting program
Source Language:	PAL-8

DECUS NO. 12-158
FASTCOPY, A Fast LINCtape Copier for 4K PDP-12's
Marka. Hyde, Jamesville-DeWitt Central Schools,
Jamesville, New York
(FASTCOPY provides the 4K PDP-12 user with an efficient
means for copying data stored on LINCtape. It operates
properly with tapes containing any number of blocks and with
blocks of up to 3584 (7000 octal) words. The program
adjusts itself to copy the largest group of blocks that will fit
in 4K at one time. For example, 256 word blocks are copied
in groups of 14(10). The program also operates correctly on
groups of blocks that extend across the transition from negative
to positive block numbers.
Minimum Hardware:	PDP-12, TTY, 2 LINCtape drives
Other Programs Needed:	PAL12A (DECUS NO. 12-77) and
			User's Monitor Command (DECUS
			NO. 12-122). Both are included
			on tape
Storage Requirement:	4K
Source Language:	PAL12A

DECUS NO. 12-159
PLAYBOY
Walter Weiskopf and James C. Good,
Jamesville-DeWitt Central Schools, DeWitt, New York
PLAYBOY prints the image of the playboy bunny in either of
2 colors; black or white, on an 8 1/2 x 11 paper form.
Minimum Hardware:	PDP-12, LSBE or LP0B Line
			Printer (The printing device
			IOTs can easily be-changed.)
Other Programs Needed:	PAL12A (DECUS NO. 12-77)
Storage Requirement:	4K
Source Language:	PAL12A

DECUS NO. 12-160
CCTGEN - Carriage Control Tape Generator
James C. Good, Jamesville-DeWitt Central Schools,
DeWitt, New York
CCTGEN will generate carriage control tapes whose form and
tab stops are at intervals defined by the operator.
Minimum Hardware:	PDP-12, ASR33
Other Programs Needed:	PAL12A (DECUS NO. 12-77)
Storage Requirement:	4K
Source Language:	PAL12A

DECUS NO. 12-161
BIGCHARS
Roy D. Eassa, Jamesville-DeWitt Central Schools,
DeWitt, New York
BIGCHARS displays 5 X 7 characters on the VR12 scope and
prints enlarged patterns on the LS8E line printer. All printing
teletype characters are acceptable.
Minimum Hardware:	PDP-12, VR12 Scope, ASR33,
			LSBE
Other Programs Needed:	PAL12A (DECUS NO. 12-77)
Storage Requirement:	4K
Source Language:	PAL12A

DECUS NO. 12-162
COREDIT
Roy D. Eassa, Jamesville-DeWitt Central Schools, DeWitt,
New York
COREDIT displays core locations on the scope, prints them
out, allows modifications and has a word search option.
Minimum Hardware:	PDP-12, VR12 scope, ASR33
Other Programs Needed:	PAL12A and User's Monitor
			Command (DECUS NOS. 12-77
			and 12-122)
Storage Requirement:	4K
Source Language:	PAL12A

DECUS NO. 12-163
AD74 - High Speed Analog to Digital Conversion Program
Barrie F. Walker, Institute of Oceanography,
University of British Columbia, Vancouver, Canada
AD74 is a fast analog to digital conversion program. Analog
data input is through the standard 16 channel PDP-12 A-D
converter. Digitized data is recorded on 9 track tape with
the IBM compatible TU-10 drive.
<P>
For a single input channel the maximum rate is about 16000
samples/second. This limit is made possible by using the
RK8 as a buffer between core and tape.
<P>
For applications where an RK8 is not available, or where
high speed is not essential, data may be dumped on tape
without disk buffering at a maximum rate of about 5000
samples/second.
Minimum Hardware:	PDP-12 A-D inputs, TU-10 tape,
			KW-12A clock, RK8 disk (optional),
			VR12
Storage Requirement:	8K
Source Language:	DIAL

.
HEREDOC
# Don't forget the newline before HEREDOC above!

%italic = (
"Editor's Note", 1,
"Minimum Hardware", 1,
"Miscellaneous", 1,
"Other Programs Needed", 1,
"PS/8 programming system", 1,
"Restrictions", 1,
"Revised by", 1,
"Source Language", 1,
"Storage Requirement", 1,
"Storage Requirements", 1,
"Submitted by", 1,
);

#
# This little routine simplifies the handling of lines
# which end in commas, indicating they should be merged
# with the following line.
sub merge {
  local($line) = @_;
  while ($line =~ /,$/) {
#warn "merge was: $line";
    $line .= shift(@heredoc) . "\n";
#warn "merge now: $line";
  }
  return $line;
}

#
# The OCR doesn't save much by way of formatting information.
# Here we use a heuristics and knowledge of the general layout
# to try do do mark-up.
@heredoc = split(/\n/, $heredoc);
$state = 'header';
while (defined($line = shift(@heredoc))) {
  $line .= "\n"; # These were lost by split()
#print "$state: $line\n";
  $line =~ s/\r//g;
  if ($state eq 'header') {
    next if $line =~ /^$/;
    die "bad header: $line" unless $line =~ /^DECUS NO. (12-\d+[A-Z,]*)$/;
    $decus = "$1";
    $decus =~ y/A-Z/a-z/;
    warn "mkdir ../$decus\n" unless -d "../$decus";
    $state = 'title';
    $title = $author = '';
    $submitted = $revised = '';
#   print "cat >../$decus/decus-$decus.htm <<HERE\n";
    print "cat >decus-$decus.htm <<HERE\n";
  } elsif ($state eq 'title') {
    # Multi-line titles are a total hack.  We assume a single line,
    # but if an "author" line has no commas, it's part of the title.
    # (Unless a proper author line has been seen.)
    $title .= $line;
    $author = $submitted = '';
    $state = 'author';
    # Author hack for abstracts missing usual author line.
    $author = ' ' if $decus eq '12-1';
    $author = ' ' if $decus eq '12-3';
    $author = ' ' if $decus eq '12-19';
    $author = ' ' if $decus eq '12-41';
    $author = ' ' if $decus eq '12-49';
    $author = ' ' if $decus eq '12-53';
    $author = ' ' if $decus eq '12-67';
    $author = ' ' if $decus eq '12-68';
    $author = ' ' if $decus eq '12-81';
    $author = ' ' if $decus eq '12-82';
    $author = ' ' if $decus eq '12-83';
    $author = ' ' if $decus eq '12-88';
    $author = ' ' if $decus eq '12-89';
    $author = ' ' if $decus eq '12-90';
    $author = ' ' if $decus eq '12-91';
    $author = ' ' if $decus eq '12-92';
    $author = ' ' if $decus eq '12-93';
    $author = ' ' if $decus eq '12-94';
    $author = ' ' if $decus eq '12-127';
    $author = ' ' if $decus eq '12-131';
    $author = ' ' if $decus eq '12-156';
  } elsif ($state eq 'author') {
    # If there are no commas, this is really part of the title
    if (($author eq '') && ($line !~ /,/)) {
      $title .= $line;
      next; 
    }
    # We have what appears to be an author line.
    # Hack: look for a continuation if a trailing comma is detected.
    # This is the most common case, but does also require tweaking of
    # the input for less common cases.
    $author .= &merge($line);
    # We look for colon lines in the body, so we should be able
    # to identify "Submitted by" and "Revised by" lines.
    # (Each will need it's own version of the trailing comma hack.)
    $state = 'body';
    $body = '';
  } elsif ($state eq 'body') {
    # Body lines are copied through, unless there's a colon.
    if ($line =~ /^([^:]*):/) {
      # If it's a recognised case, rewrite it.
      $line =~ s/^([^:]*):(.*)/<\/div><div><I>\1<\/I>:\2/
        if defined $italic{$1};
      # Colon cases may need more markup
      if ($1 eq 'Submitted by') {
        $submitted .= &merge("$2\n");
        next;
      }
      if ($1 eq 'Revised by') {
        $revised .= &merge("$2\n");
        next;
      }
    }
    # Most bodies are just a big run-on paragraph.  Where they are
    # not, it will be necessary to edit in a <P>.
    # (12-25, for example.)
    $body .= $line;
    if ($line =~ /^$/) {
#     warn "decus: $decus\n";
#     warn "title: $title";
      print "<div style=width:50%>\n";
      chop $title;
      print "<table width=100%>\n";
      print "<td><div>$title</div>\n";
      print "<td>$decus\n";
      print "</table>\n";
#     warn "author: $author";
#     warn "submitted: $submitted";
      chop $author;
      print "<div><I>Author</I>: $author</div>\n";
      $submitted =~ s/, $//;
      print "<div><I>Submitted by</I>:$submitted</div>\n" if $submitted;
      $revised =~ s/, $//;
      print "<div><I>Revised by</I>:$revised</div>\n" if $revised;
      $body =~ s/\t/ /g;
      $body =~ s/\n*$//;
      $body .= "</div>\n<div><I>Catalog</I>: $catalog</div>\n";
      $body =~ s:\n</div>:</div>\n:g;
      $body =~ s:<div>\n*</div>\n*::g;
#     warn "body: $body";
      print "<div>$body</div>\n";
print "HERE\n";
      $state = 'header';
    }
  }
}

