# There is the interpreter, then a couple of ISR patches.
# Unfortunately, it doesn't run right with either patch.
load decus-focal8-136-pb
#load focal8-136-isr-v1-11.20.74-pb
#load focal8-136-isr-hsr-1.8.76-pb
# Starting with SR=0000 will halt, presumably to let you
# set the switches.  I don't know what's supposed to be
# in the switches, but this seems to work OK.
d sr 1
# The start/restart address is 0200.
g 0200
# Nothing interesting to look at yet, so just exit on ^E.
q
