BA	= 1check.ba 23mtch.ba 3dplot.ba aceydu.ba amazin.ba animal.ba awari.ba \
	bagles.ba banner.ba basbal.ba basket.ba batnum.ba battle.ba bingo.ba \
	blkjac.ba blkjak.ba boat.ba bomber.ba bounce.ba bowl.ba boxing.ba \
	bug.ba bulcow.ba buleye.ba bull.ba bunny.ba buzzwd.ba calndr.ba \
	canam.ba change.ba checkr.ba chemst.ba chief.ba chomp.ba civilw.ba \
	craps.ba cube.ba diamnd.ba dice.ba digits.ba dogs.ba even1.ba \
	even.ba fipfop.ba footbl.ba fotbal.ba furs.ba golf.ba gomoko.ba \
	guess.ba gunner.ba hang.ba hello.ba hex.ba hilo.ba hiq.ba hmrabi.ba \
	hockey.ba horses.ba hurkle.ba kinema.ba king.ba letter.ba life2.ba \
	life.ba litqz.ba mathdi.ba mnoply.ba monply.ba mugwmp.ba nicoma.ba \
	nim.ba number.ba orbit.ba pizza.ba poet.ba poetry.ba poker.ba qubic.ba \
	queen.ba reseq.ba revrse.ba rocket.ba rockt1.ba roulet.ba rusrou.ba \
	salvo1.ba salvo.ba signs.ba slots.ba snoopy.ba spacwr.ba splat.ba \
	stars.ba stock.ba synonm.ba target.ba tictac.ba tower.ba train.ba \
	trap.ba ugly.ba war2.ba war.ba wekday.ba word.ba yahtze.ba zoop.ba
NOTBA	= animal.de monply.b1 spacwr.in
GAMES	= $(BA) $(NOTBA)

all:	$(GAMES)

%.ba:	../%.ba
	cp $< $@

animal.de: ../animal.de
	cp $< $@

monply.b1: ../monply.b1
	cp $< $@

spacwr.in: ../spacwr.in
	cp $< $@

