#!/usr/bin/perl

#
# Look for a directory/project for each title.
# Report on directories found, if any.
#

foreach $f (@ARGV) {
  open(INPUT, $f) || die "$f: $!";
  while (<INPUT>) {
    die "Invalid input line: $_" unless /(.*)\t(.*)$/;
    ($vers, $title) = ($1, $2);
    # Trim the version number
#BUGBUG
next if $vers =~ /F-85/;
next if $vers =~ /C-9/;
    $item = $vers;
    $item =~ s/.$// if $item =~ /^dec/;
    $item =~ s/.$// if $item =~ /^maindec/;
    if (-d $item) {
#     print "Found $item for $vers:$title\n";
    } else {
      warn "No $item for $vers:$title\n";
    }
  }
}
