$JOB
.ASSIGN RXA1 OUT
.ZERO OUT:
.COPY OUT:<RKB0:MUSIC.PA
.COPY OUT:<RKB0:PLAYOV.PA
.COPY OUT:<RKB0:PLAYOV.BN
.COPY OUT:<RKB0:MUSIC2.MU
.COPY OUT:<RKB0:MUSIC3.MU
.COPY OUT:<RKB0:MUSIC5.MU
.COPY OUT:<RKB0:USA.MU
.COPY OUT:<RKB0:MUSIC6.MU
.COPY OUT:<RKB0:YANKEE.MU
.COPY OUT:<RKB0:INV210.MU
.COPY OUT:<RKB0:INV213.MU
.COPY OUT:<RKB0:FUGUE.MU
.COPY OUT:<RKB0:ENTER.MU
.COPY OUT:<RKB0:INV201.MU
.COPY OUT:<RKB0:INV212.MU
.COPY OUT:<RKB0:INV214.MU
.COPY OUT:<RKB0:FIFTH1.MU
.COPY OUT:<RKB0:FIFTH3.MU
.COPY OUT:<RKB0:MAPLE.MU
.COPY OUT:<RKB0:MUSIC1.MU
.COPY OUT:<RKB0:MINUET.MU
.COPY OUT:<RKB0:GMINOR.MU
.COPY OUT:<RKB0:INV315.MU
.COPY OUT:<RKB0:MINUTE.MU
.COPY OUT:<RKB0:1TNSLD.MU
.COPY OUT:<RKB0:JCOOK2.MU
$END
