; "Toggle in" the RIM loader
dep 07756 6014
dep 07757 6011
dep 07760 5357
dep 07761 6016
dep 07762 7106
dep 07763 7006
dep 07764 7510
dep 07765 5374
dep 07766 7006
dep 07767 6011
dep 07770 5367
dep 07771 6016
dep 07772 7420
dep 07773 3776
dep 07774 3376
dep 07775 5357
dep 07776 0000

; To set up additional terminals for Edu10, connect thru PuTTY with
; a TelNet connection on localhost with port 12166. this connection
; can be established before pressing Start on the PiDP-8/i so that
; Edu20C's READY prompt comes out on both terminals at the same time
; NOTE1: up to 5 additional terminals are supported in this script
; NOTE2: once ttix is attached, it remains attached until simh is
; exited. just <ctrl/e> exit then "pidp8i start" to get back going
; again
; NOTE3: the console terminal "owns" PTR: and PTP:. if the second
; terminal needs ptr/ptp it must be done thru the console. as well,
; all console simh activity suspends both terminals
; NOTE4: Edu10 probably doesn't actually allow extra terminals, so
; this section is likely irrelevant.
set ttix lines=5
att ttix 12166

; Load the self starting BIN loader.  The BIN loader will self start,
; then load the BIN image, then start that.
; 
att ptr dec-08-ed10-a-pb
g 7756
q
