C
C
C
C       HISTOGRAM:  A DEMONSTRATION PROGRAM
C THIS PROGRAM GENERATES A LATENCY HISTOGRAM FROM
C      A WAVEFORM ENTERED AT CLOCK INPUT #3
C
C
C
C ZERO TIME INTERVAL BINS
        DIMENSION IA(100)
1       DO 5 I=1,100,1
5       IA(I)=0
C READ CLOCK RATE (0-7)
        READ (1,101)IRATE
101     FORMAT('CLOCK RATE',I2)
C SET CLOCK TO SELECTED RATE; ENABLE INTERUPT ON CHANNEL #3
        CALL CLKSET(3,IRATE,0,0,0,3)
C COUNT 1000 PULSES
        DO 10 I=1,1000,1
        CALL CLKRUN (I1,I2,I3,ICN)
C INCREMENT BIN EQUAL TO LATENCY
7       IA(ICN)=IA(ICN)+1
10      CONTINUE
C OUTPUT BIN CONTENTS IN A 10X10 TABLE WITH EACH BIN EQUAL TO
C AN INTERVAL OF ONE CLOCK COUNT
        WRITE(1,100) (IA(I),I=1,100)
100     FORMAT (10(1X,I6))
C DISPLAY HISTOGRAM ON SCOPE UNTIL SENSE SWITCH #0 IS RAISED
20      DO 25 I=1,100,1
        CALL DISP (I*5,IA(I)-250)
25      CONTINUE
        IF (ISNS(0)) 20,20,30
30      GOTO 1
        END
