# set model pdp12
#set lpt disable
#set ttix disable
#set ttox disable
#set rk disable
#set rx disable
#set dt disable
#set mt disable
#set df disable
#load 12604.bin
#load 20292.bin
#load 38004.bin
load 50710.bin
d 2646 6132
br 1
g 0200
nobr
g 0200
