load maindec-08-djkka-b-pb
load maindec-08-djkka-c-pb
; Default is to run silently because no console provided.
; Here we set the console bit, so we can see what's going on.
d 0021 4000
; Uncomment SR deposit to allow more than one pass.
d sr 0400
g 0200
