#!/bin/bash
dtc -O dtb -o p9_25-00A0.dtbo -b 0 -@ p9_25-00A0.dts
cp p9_25-00A0.dtbo /lib/firmware
echo p9_25:00A0 > /sys/devices/bone_capemgr.*/slots
#dtc -O dtb -o ptest-00A0.dtbo -b 0 -@ ptest-00A0.dts
#cp ptest-00A0.dtbo /lib/firmware
#echo ptest:00A0 > /sys/devices/bone_capemgr.*/slots
# 50 dir, 60 enable
pins="2 4 50 60 116 117"
for pin in $pins; do
   echo $pin > /sys/class/gpio/export
   echo high > /sys/class/gpio/gpio$pin/direction
done
echo low > /sys/class/gpio/gpio60/direction
